In [2]:
### I identified factors I thought were interesting from the WorldBank Data and exported them to an excel spreadsheet.
### From here I broke them into 6 categories - Economic, Social, Health, Education, Infrastructure, and Other
### Next pulled these factors out of the sheet into dictionaries to be used in the API calls

import xlrd

loc = ('factors_categories_short.xls')  ### May have to refactor when pushed to an instance of GIT
wb = xlrd.open_workbook(loc)

# Economic Factors
sheet_econ = wb.sheet_by_index(1)  ### sheet 2 (index 1) of excel sheet
economic_dict = {}  ### create an empty dictionary
for i in range(1, sheet_econ.nrows):  ### skip first row to account for headers
    factor_code = sheet_econ.cell_value(i, 0)  ### ith row, first column
    factor_name = sheet_econ.cell_value(i, 1)  ### ith row, second column
    economic_dict[factor_code] = factor_name  ### add item to dictionary

### Social Factors
sheet_social = wb.sheet_by_index(2)  ### sheet 3
social_dict = {}

for i in range(1, sheet_social.nrows):
    factor_code = sheet_social.cell_value(i, 0)
    factor_name = sheet_social.cell_value(i, 1)
    social_dict[factor_code] = factor_name

### Health Factors
sheet_health = wb.sheet_by_index(3)  ### sheet 4
health_dict = {}
for i in range(1, sheet_health.nrows):
    factor_code = sheet_health.cell_value(i, 0)
    factor_name = sheet_health.cell_value(i, 1)
    health_dict[factor_code] = factor_name

### Education Factors
sheet_ed = wb.sheet_by_index(4)  ### sheet 5
education_dict = {}
for i in range(1, sheet_ed.nrows):
    factor_code = sheet_ed.cell_value(i, 0)
    factor_name = sheet_ed.cell_value(i, 1)
    education_dict[factor_code] = factor_name

### Infrastructure Factors
sheet_infra = wb.sheet_by_index(5)  ### sheet 6
infra_dict = {}
for i in range(1, sheet_infra.nrows):
    factor_code = sheet_infra.cell_value(i, 0)
    factor_name = sheet_infra.cell_value(i, 1)
    infra_dict[factor_code] = factor_name

### Other Factors
sheet_other = wb.sheet_by_index(6)  ### sheet 7
other_dict = {}
for i in range(1, sheet_other.nrows):
    factor_code = sheet_other.cell_value(i, 0)
    factor_name = sheet_other.cell_value(i, 1)
    other_dict[factor_code] = factor_name

In [3]:
### check to see if dictionary was populated
print("Full Economic Factory Dictionary:")
print(economic_dict)
print('-------------------------------------------------------------------')

### check to see if keys can easily be accessed
print("Economic Factor Codes:")
for code in education_dict.keys():
    print(code)
print('-------------------------------------------------------------------')

### check to see if values can easily be accessed
print("Full Economic Factor Name:")
for name in other_dict.values():
    print(name)
print('-------------------------------------------------------------------')

Full Economic Factory Dictionary:
{'NY.ADJ.NNTY.KD.ZG': 'Adjusted net national income (annual % growth)', 'NY.ADJ.NNAT.GN.ZS': 'Adjusted savings: net national savings (% of GNI)', 'MS.MIL.TOTL.TF.ZS': 'Armed forces personnel (% of total labor force)', 'IC.FRM.BRIB.ZS': 'Bribery incidence (% of firms experiencing at least one bribe payment request)', 'GC.DOD.TOTL.GD.ZS': 'Central government debt, total (% of GDP)', 'GC.XPN.COMP.ZS': 'Compensation of employees (% of expense)', 'per_allsp.cov_pop_tot': 'Coverage of social protection and labor programs (% of population)', 'SL.EMP.TOTL.SP.NE.ZS': 'Employment to population ratio, 15+, total (%) (national estimate)', 'GC.XPN.TOTL.GD.ZS': 'Expense (% of GDP)', 'NY.GDP.MKTP.KD.ZG': 'GDP growth (annual %)', 'NY.GNP.MKTP.KD.ZG': 'GNI growth (annual %)', 'SI.DST.10TH.10': 'Income share held by highest 10%', 'SI.DST.FRST.10': 'Income share held by lowest 10%', 'FP.CPI.TOTL.ZG': 'Inflation, consumer prices (annual %)', 'MS.MIL.XPND.ZS': 'Military expenditure (% of general government expenditure)', 'GC.TAX.TOTL.GD.ZS': 'Tax revenue (% of GDP)', 'NE.TRD.GNFS.ZS': 'Trade (% of GDP)'}
-------------------------------------------------------------------
Economic Factor Codes:
SE.SEC.UNER.LO.ZS
SE.COM.DURS
SE.XPD.CTOT.ZS
SE.TER.CUAT.BA.ZS
SE.PRM.CUAT.ZS
SE.XPD.TOTL.GB.ZS
SL.TLF.BASC.ZS
SL.TLF.ADVN.ZS
SE.ADT.LITR.ZS
SE.PRM.CMPT.ZS
SE.PRM.DURS
SE.PRM.ENRL.TC.ZS
SE.PRM.ENRR
SL.UEM.NEET.ZS
SE.PRM.TCAQ.ZS
-------------------------------------------------------------------
Full Economic Factor Name:
Firms competing against unregistered firms (% of firms)
Firms expected to give gifts in meetings with tax officials (% of firms)
Firms experiencing losses due to theft and vandalism (% of firms)
Intentional homicides (per 100,000 people)
Internally displaced persons, total displaced by conflict and violence (number of people)
International migrant stock (% of population)
Labor tax and contributions (% of commercial profits)
Net official development assistance and official aid received (constant 2015 US$)
Population ages 0-14 (% of total population)
Population ages 15-64 (% of total population)
Population ages 65 and above (% of total population)
Population density (people per sq. km of land area)
Population growth (annual %)
Population living in slums (% of urban population)
Population, total
Presence of peace keepers (number of troops, police, and military observers in mandate)
Rural population
Rural population growth (annual %)
Urban population
Urban population growth (annual %)
-------------------------------------------------------------------

In [4]:
### Next I needed to pull out all of the country codes that World Bank uses for their Indicators
loc_cc = ('cc_shortname.xls') ### may need to refactor
wb_cc = xlrd.open_workbook(loc_cc)
sheet_cc = wb_cc.sheet_by_index(0) ### sheet 1

cc_dict = {}   ### create dictionary to hold country codes, names

for i in range(47, sheet_cc.nrows): ### index 47 is start of country codes, previous lines are groupings/regions
    cc = sheet_cc.cell_value(i,1) ### ith row, second column
    country_name = sheet_cc.cell_value(i, 0) ### ith row, first column
    cc_dict[cc] = country_name

In [5]:
### check to see if dictionary was populated
print("Full Country Code Dictionary:")
print(cc_dict)
print('-------------------------------------------------------------------')

### check to see if keys can easily be accessed
print("Country Codes:")
for cc in cc_dict.keys():
    print(cc)
print('-------------------------------------------------------------------')

### check to see if values can easily be accessed
print("Country Names:")
for name in cc_dict.values():
    print(name)
print('-------------------------------------------------------------------')

Full Country Code Dictionary:
{'AFG': 'Afghanistan', 'ALB': 'Albania', 'DZA': 'Algeria', 'ASM': 'American Samoa', 'AND': 'Andorra', 'AGO': 'Angola', 'ATG': 'Antigua and Barbuda', 'ARG': 'Argentina', 'ARM': 'Armenia', 'ABW': 'Aruba', 'AUS': 'Australia', 'AUT': 'Austria', 'AZE': 'Azerbaijan', 'BHS': 'Bahamas, The', 'BHR': 'Bahrain', 'BGD': 'Bangladesh', 'BRB': 'Barbados', 'BLR': 'Belarus', 'BEL': 'Belgium', 'BLZ': 'Belize', 'BEN': 'Benin', 'BMU': 'Bermuda', 'BTN': 'Bhutan', 'BOL': 'Bolivia', 'BIH': 'Bosnia and Herzegovina', 'BWA': 'Botswana', 'BRA': 'Brazil', 'VGB': 'British Virgin Islands', 'BRN': 'Brunei Darussalam', 'BGR': 'Bulgaria', 'BFA': 'Burkina Faso', 'BDI': 'Burundi', 'CPV': 'Cabo Verde', 'KHM': 'Cambodia', 'CMR': 'Cameroon', 'CAN': 'Canada', 'CYM': 'Cayman Islands', 'CAF': 'Central African Republic', 'TCD': 'Chad', 'CHI': 'Channel Islands', 'CHL': 'Chile', 'CHN': 'China', 'COL': 'Colombia', 'COM': 'Comoros', 'COD': 'Congo, Dem. Rep.', 'COG': 'Congo, Rep.', 'CRI': 'Costa Rica', 'CIV': "Cote d'Ivoire", 'HRV': 'Croatia', 'CUB': 'Cuba', 'CUW': 'Curacao', 'CYP': 'Cyprus', 'CZE': 'Czech Republic', 'DNK': 'Denmark', 'DJI': 'Djibouti', 'DMA': 'Dominica', 'DOM': 'Dominican Republic', 'ECU': 'Ecuador', 'EGY': 'Egypt, Arab Rep.', 'SLV': 'El Salvador', 'GNQ': 'Equatorial Guinea', 'ERI': 'Eritrea', 'EST': 'Estonia', 'SWZ': 'Eswatini', 'ETH': 'Ethiopia', 'FRO': 'Faroe Islands', 'FJI': 'Fiji', 'FIN': 'Finland', 'FRA': 'France', 'PYF': 'French Polynesia', 'GAB': 'Gabon', 'GMB': 'Gambia, The', 'GEO': 'Georgia', 'DEU': 'Germany', 'GHA': 'Ghana', 'GIB': 'Gibraltar', 'GRC': 'Greece', 'GRL': 'Greenland', 'GRD': 'Grenada', 'GUM': 'Guam', 'GTM': 'Guatemala', 'GIN': 'Guinea', 'GNB': 'Guinea-Bissau', 'GUY': 'Guyana', 'HTI': 'Haiti', 'HND': 'Honduras', 'HKG': 'Hong Kong SAR, China', 'HUN': 'Hungary', 'ISL': 'Iceland', 'IND': 'India', 'IDN': 'Indonesia', 'IRN': 'Iran, Islamic Rep.', 'IRQ': 'Iraq', 'IRL': 'Ireland', 'IMN': 'Isle of Man', 'ISR': 'Israel', 'ITA': 'Italy', 'JAM': 'Jamaica', 'JPN': 'Japan', 'JOR': 'Jordan', 'KAZ': 'Kazakhstan', 'KEN': 'Kenya', 'KIR': 'Kiribati', 'PRK': "Korea, Dem. People's Rep.", 'KOR': 'Korea, Rep.', 'XKX': 'Kosovo', 'KWT': 'Kuwait', 'KGZ': 'Kyrgyz Republic', 'LAO': 'Lao PDR', 'LVA': 'Latvia', 'LBN': 'Lebanon', 'LSO': 'Lesotho', 'LBR': 'Liberia', 'LBY': 'Libya', 'LIE': 'Liechtenstein', 'LTU': 'Lithuania', 'LUX': 'Luxembourg', 'MAC': 'Macao SAR, China', 'MDG': 'Madagascar', 'MWI': 'Malawi', 'MYS': 'Malaysia', 'MDV': 'Maldives', 'MLI': 'Mali', 'MLT': 'Malta', 'MHL': 'Marshall Islands', 'MRT': 'Mauritania', 'MUS': 'Mauritius', 'MEX': 'Mexico', 'FSM': 'Micronesia, Fed. Sts.', 'MDA': 'Moldova', 'MCO': 'Monaco', 'MNG': 'Mongolia', 'MNE': 'Montenegro', 'MAR': 'Morocco', 'MOZ': 'Mozambique', 'MMR': 'Myanmar', 'NAM': 'Namibia', 'NPL': 'Nepal', 'NLD': 'Netherlands', 'NCL': 'New Caledonia', 'NZL': 'New Zealand', 'NIC': 'Nicaragua', 'NER': 'Niger', 'NGA': 'Nigeria', 'MKD': 'North Macedonia', 'MNP': 'Northern Mariana Islands', 'NOR': 'Norway', 'OMN': 'Oman', 'PAK': 'Pakistan', 'PLW': 'Palau', 'PAN': 'Panama', 'PNG': 'Papua New Guinea', 'PRY': 'Paraguay', 'PER': 'Peru', 'PHL': 'Philippines', 'POL': 'Poland', 'PRT': 'Portugal', 'PRI': 'Puerto Rico', 'QAT': 'Qatar', 'ROU': 'Romania', 'RUS': 'Russian Federation', 'RWA': 'Rwanda', 'WSM': 'Samoa', 'SMR': 'San Marino', 'STP': 'Sao Tome and Principe', 'SAU': 'Saudi Arabia', 'SEN': 'Senegal', 'SRB': 'Serbia', 'SYC': 'Seychelles', 'SLE': 'Sierra Leone', 'SGP': 'Singapore', 'SXM': 'Sint Maarten (Dutch part)', 'SVK': 'Slovak Republic', 'SVN': 'Slovenia', 'SLB': 'Solomon Islands', 'SOM': 'Somalia', 'ZAF': 'South Africa', 'SSD': 'South Sudan', 'ESP': 'Spain', 'LKA': 'Sri Lanka', 'KNA': 'St. Kitts and Nevis', 'LCA': 'St. Lucia', 'MAF': 'St. Martin (French part)', 'VCT': 'St. Vincent and the Grenadines', 'SDN': 'Sudan', 'SUR': 'Suriname', 'SWE': 'Sweden', 'CHE': 'Switzerland', 'SYR': 'Syrian Arab Republic', 'TJK': 'Tajikistan', 'TZA': 'Tanzania', 'THA': 'Thailand', 'TLS': 'Timor-Leste', 'TGO': 'Togo', 'TON': 'Tonga', 'TTO': 'Trinidad and Tobago', 'TUN': 'Tunisia', 'TUR': 'Turkey', 'TKM': 'Turkmenistan', 'TCA': 'Turks and Caicos Islands', 'TUV': 'Tuvalu', 'UGA': 'Uganda', 'UKR': 'Ukraine', 'ARE': 'United Arab Emirates', 'GBR': 'United Kingdom', 'USA': 'United States', 'URY': 'Uruguay', 'UZB': 'Uzbekistan', 'VUT': 'Vanuatu', 'VEN': 'Venezuela, RB', 'VNM': 'Vietnam', 'VIR': 'Virgin Islands (U.S.)', 'PSE': 'West Bank and Gaza', 'YEM': 'Yemen, Rep.', 'ZMB': 'Zambia', 'ZWE': 'Zimbabwe'}
-------------------------------------------------------------------
Country Codes:
AFG
ALB
DZA
ASM
AND
AGO
ATG
ARG
ARM
ABW
AUS
AUT
AZE
BHS
BHR
BGD
BRB
BLR
BEL
BLZ
BEN
BMU
BTN
BOL
BIH
BWA
BRA
VGB
BRN
BGR
BFA
BDI
CPV
KHM
CMR
CAN
CYM
CAF
TCD
CHI
CHL
CHN
COL
COM
COD
COG
CRI
CIV
HRV
CUB
CUW
CYP
CZE
DNK
DJI
DMA
DOM
ECU
EGY
SLV
GNQ
ERI
EST
SWZ
ETH
FRO
FJI
FIN
FRA
PYF
GAB
GMB
GEO
DEU
GHA
GIB
GRC
GRL
GRD
GUM
GTM
GIN
GNB
GUY
HTI
HND
HKG
HUN
ISL
IND
IDN
IRN
IRQ
IRL
IMN
ISR
ITA
JAM
JPN
JOR
KAZ
KEN
KIR
PRK
KOR
XKX
KWT
KGZ
LAO
LVA
LBN
LSO
LBR
LBY
LIE
LTU
LUX
MAC
MDG
MWI
MYS
MDV
MLI
MLT
MHL
MRT
MUS
MEX
FSM
MDA
MCO
MNG
MNE
MAR
MOZ
MMR
NAM
NPL
NLD
NCL
NZL
NIC
NER
NGA
MKD
MNP
NOR
OMN
PAK
PLW
PAN
PNG
PRY
PER
PHL
POL
PRT
PRI
QAT
ROU
RUS
RWA
WSM
SMR
STP
SAU
SEN
SRB
SYC
SLE
SGP
SXM
SVK
SVN
SLB
SOM
ZAF
SSD
ESP
LKA
KNA
LCA
MAF
VCT
SDN
SUR
SWE
CHE
SYR
TJK
TZA
THA
TLS
TGO
TON
TTO
TUN
TUR
TKM
TCA
TUV
UGA
UKR
ARE
GBR
USA
URY
UZB
VUT
VEN
VNM
VIR
PSE
YEM
ZMB
ZWE
-------------------------------------------------------------------
Country Names:
Afghanistan
Albania
Algeria
American Samoa
Andorra
Angola
Antigua and Barbuda
Argentina
Armenia
Aruba
Australia
Austria
Azerbaijan
Bahamas, The
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bermuda
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
British Virgin Islands
Brunei Darussalam
Bulgaria
Burkina Faso
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Cayman Islands
Central African Republic
Chad
Channel Islands
Chile
China
Colombia
Comoros
Congo, Dem. Rep.
Congo, Rep.
Costa Rica
Cote d'Ivoire
Croatia
Cuba
Curacao
Cyprus
Czech Republic
Denmark
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt, Arab Rep.
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Faroe Islands
Fiji
Finland
France
French Polynesia
Gabon
Gambia, The
Georgia
Germany
Ghana
Gibraltar
Greece
Greenland
Grenada
Guam
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Honduras
Hong Kong SAR, China
Hungary
Iceland
India
Indonesia
Iran, Islamic Rep.
Iraq
Ireland
Isle of Man
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Korea, Dem. People's Rep.
Korea, Rep.
Kosovo
Kuwait
Kyrgyz Republic
Lao PDR
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
Macao SAR, China
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia, Fed. Sts.
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Myanmar
Namibia
Nepal
Netherlands
New Caledonia
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Northern Mariana Islands
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Puerto Rico
Qatar
Romania
Russian Federation
Rwanda
Samoa
San Marino
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Sint Maarten (Dutch part)
Slovak Republic
Slovenia
Solomon Islands
Somalia
South Africa
South Sudan
Spain
Sri Lanka
St. Kitts and Nevis
St. Lucia
St. Martin (French part)
St. Vincent and the Grenadines
Sudan
Suriname
Sweden
Switzerland
Syrian Arab Republic
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Tonga
Trinidad and Tobago
Tunisia
Turkey
Turkmenistan
Turks and Caicos Islands
Tuvalu
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Uruguay
Uzbekistan
Vanuatu
Venezuela, RB
Vietnam
Virgin Islands (U.S.)
West Bank and Gaza
Yemen, Rep.
Zambia
Zimbabwe
-------------------------------------------------------------------

In [6]:
### Create a database for this

import psycopg2

conn = psycopg2.connect (
    database="postgres", user='postgres', password='password', host='127.0.0.1', port='5432'
)

conn.autocommit = True

cursor = conn.cursor()

sql = '''CREATE database unrestDatabase''';

cursor.execute(sql)
print("Database created successfully.......")

conn.close()

Database created successfully.......

In [7]:
### Create country and indicators tables

conn = psycopg2.connect (
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

conn.autocommit = True

cursor = conn.cursor()

sql = '''
DROP TABLE IF EXISTS countries; 
CREATE TABLE countries(
    COUNTRY_NAME CHAR(50) NOT NULL,
    COUNTRY_CODE CHAR(3) NOT NULL
);
DROP TABLE IF EXISTS econ_factors; 
CREATE TABLE econ_factors(
    INDICATOR_CODE CHAR(25) NOT NULL,
    INDICATOR_NAME CHAR(255) NOT NULL
);

DROP TABLE IF EXISTS social_factors; 
CREATE TABLE social_factors(
    INDICATOR_CODE CHAR(25) NOT NULL,
    INDICATOR_NAME CHAR(255) NOT NULL
);

DROP TABLE IF EXISTS health_factors; 
CREATE TABLE health_factors(
    INDICATOR_CODE CHAR(25) NOT NULL,
    INDICATOR_NAME CHAR(255) NOT NULL
);

DROP TABLE IF EXISTS education_factors; 
CREATE TABLE education_factors(
    INDICATOR_CODE CHAR(25) NOT NULL,
    INDICATOR_NAME CHAR(255) NOT NULL
);

DROP TABLE IF EXISTS infra_factors; 
CREATE TABLE infra_factors(
    INDICATOR_CODE CHAR(25) NOT NULL,
    INDICATOR_NAME CHAR(255) NOT NULL
);

DROP TABLE IF EXISTS other_factors; 
CREATE TABLE other_factors(
    INDICATOR_CODE CHAR(25) NOT NULL,
    INDICATOR_NAME CHAR(255) NOT NULL
);
'''

cursor.execute(sql)
print("Tables created successfully.......")

conn.close()

Tables created successfully.......

In [8]:
### populate tables from dictionaries created using excel sheets

try:
    connection = psycopg2.connect(user ='postgres',
                                 password='password',
                                 host='127.0.0.1',
                                 port='5432',
                                 database='unrestdatabase')
    cursor = connection.cursor()
    
    insert_countries = """ INSERT INTO countries (COUNTRY_NAME, COUNTRY_CODE) VALUES (%s,%s)"""
    insert_econ_factors = """ INSERT INTO econ_factors (INDICATOR_CODE, INDICATOR_NAME) VALUES (%s, %s)"""
    insert_social_factors = """ INSERT INTO social_factors (INDICATOR_CODE, INDICATOR_NAME) VALUES (%s, %s)"""    
    insert_health_factors = """ INSERT INTO health_factors (INDICATOR_CODE, INDICATOR_NAME) VALUES (%s, %s)"""    
    insert_education_factors = """ INSERT INTO education_factors (INDICATOR_CODE, INDICATOR_NAME) VALUES (%s, %s)"""    
    insert_infra_factors = """ INSERT INTO infra_factors (INDICATOR_CODE, INDICATOR_NAME) VALUES (%s, %s)"""
    insert_other_factors = """ INSERT INTO other_factors (INDICATOR_CODE, INDICATOR_NAME) VALUES (%s, %s)"""
    
    for k, v in cc_dict.items():
        record_to_insert = (v, k)
        cursor.execute(insert_countries, record_to_insert)
        connection.commit()
    print("Country Records successfully inserted")

    for k, v in economic_dict.items():
        rec_to_insert = (k, v)
        cursor.execute(insert_econ_factors, rec_to_insert)
        connection.commit()
    print("Economic Factors Records successfully inserted")
    
    for k, v in social_dict.items():
        rec_to_insert = (k, v)
        cursor.execute(insert_social_factors, rec_to_insert)
        connection.commit()
    print("Social Factors Records successfully inserted")

    for k, v in health_dict.items():
        rec_to_insert = (k, v)
        cursor.execute(insert_health_factors, rec_to_insert)
        connection.commit()
    print("Health Factors Records successfully inserted")    
    
    for k, v in education_dict.items():
        rec_to_insert = (k, v)
        cursor.execute(insert_education_factors, rec_to_insert)
        connection.commit()
    print("Education Factors Records successfully inserted")
    
    for k, v in infra_dict.items():
        rec_to_insert = (k, v)
        cursor.execute(insert_infra_factors, rec_to_insert)
        connection.commit()
    print("Infrastructure Factors Records successfully inserted")
    
    for k, v in other_dict.items():
        rec_to_insert = (k, v)
        cursor.execute(insert_other_factors, rec_to_insert)
        connection.commit()
    print("Other Factors Records successfully inserted")
    
except (Exception, psycopg2.Error) as error :
    if(connection):
        print("Failed to insert records ", error)

finally:
    #closing database connection.
    if(connection):
        cursor.close()
        connection.close()
        print("PostgreSQL connection is closed")

Country Records successfully inserted
Economic Factors Records successfully inserted
Social Factors Records successfully inserted
Health Factors Records successfully inserted
Education Factors Records successfully inserted
Infrastructure Factors Records successfully inserted
Other Factors Records successfully inserted
PostgreSQL connection is closed

In [9]:
### Create SQL tables to store WorldBank Economic data by year pulled from API

conn = psycopg2.connect (
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

conn.autocommit = True

cursor = conn.cursor()

insert_statement_10 = 'DROP TABLE IF EXISTS economic_2010; CREATE TABLE economic_2010("COUNTRY.CODE" CHAR(3),'
insert_statement_11 = 'DROP TABLE IF EXISTS economic_2011; CREATE TABLE economic_2011("COUNTRY.CODE" CHAR(3),'
insert_statement_12 = 'DROP TABLE IF EXISTS economic_2012; CREATE TABLE economic_2012("COUNTRY.CODE" CHAR(3),'
insert_statement_13 = 'DROP TABLE IF EXISTS economic_2013; CREATE TABLE economic_2013("COUNTRY.CODE" CHAR(3),'
insert_statement_14 = 'DROP TABLE IF EXISTS economic_2014; CREATE TABLE economic_2014("COUNTRY.CODE" CHAR(3),'
insert_statement_15 = 'DROP TABLE IF EXISTS economic_2015; CREATE TABLE economic_2015("COUNTRY.CODE" CHAR(3),'
insert_statement_16 = 'DROP TABLE IF EXISTS economic_2016; CREATE TABLE economic_2016("COUNTRY.CODE" CHAR(3),'
insert_statement_17 = 'DROP TABLE IF EXISTS economic_2017; CREATE TABLE economic_2017("COUNTRY.CODE" CHAR(3),'
insert_statement_18 = 'DROP TABLE IF EXISTS economic_2018; CREATE TABLE economic_2018("COUNTRY.CODE" CHAR(3),'
insert_statement_19 = 'DROP TABLE IF EXISTS economic_2019; CREATE TABLE economic_2019("COUNTRY.CODE" CHAR(3),'

count = 0
column_headers = ""
for key in economic_dict.keys():
    column_headers = column_headers + '"' + key + '"' + " CHAR(255)"
    count += 1
    if count < len(economic_dict):
        column_headers = column_headers + ", "
        column_headers
    else:
        column_headers = column_headers + ");"
        column_headers

insert_statement_10 = insert_statement_10 + column_headers
insert_statement_11 = insert_statement_11 + column_headers
insert_statement_12 = insert_statement_12 + column_headers
insert_statement_13 = insert_statement_13 + column_headers
insert_statement_14 = insert_statement_14 + column_headers
insert_statement_15 = insert_statement_15 + column_headers
insert_statement_16 = insert_statement_16 + column_headers
insert_statement_17 = insert_statement_17 + column_headers
insert_statement_18 = insert_statement_18 + column_headers
insert_statement_19 = insert_statement_19 + column_headers

cursor.execute(insert_statement_10)
cursor.execute(insert_statement_11)
cursor.execute(insert_statement_12)
cursor.execute(insert_statement_13)
cursor.execute(insert_statement_14)
cursor.execute(insert_statement_15)
cursor.execute(insert_statement_16)
cursor.execute(insert_statement_17)
cursor.execute(insert_statement_18)
cursor.execute(insert_statement_19)

print("Economic tables created successfully.......")

conn.close()

Economic tables created successfully.......

In [10]:
#### Scratch for accessing data from database
import requests
import json
import pandas as pd
import time

# try:
connection = psycopg2.connect(
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

cursor = connection.cursor()

countries_query = "select country_code from countries"
cursor.execute(countries_query)
print ("Fetching country codes")
countries = cursor.fetchall()

cc_list = []

for cc in countries:
    cc_list.append(cc[0])
print ("CC list created")

econ_indicator_query = "select indicator_code from econ_factors"
cursor.execute(econ_indicator_query)
print ("Fetching Econ Indicator Codes")
econ_indicators = cursor.fetchall()

econ_indicator_list = []
for indicator in econ_indicators:
    econ_indicator_list.append(indicator[0].strip())
print ("Indicator code list created")

start_time = time.time()
for cc in cc_list:
    
    ### As api calls time out, I don't want to repeat table entries, so checking if they exist and moving on if they do
    check_statement = 'select * from economic_2010 where "COUNTRY.CODE" =  ' + "'" + cc + "'"
    cursor.execute(check_statement)
    if bool(cursor.rowcount):
        continue
        
    values_dict = {'COUNTRY.CODE': cc}   ### dictionary to hold values pulled from API
    for indicator in econ_indicators:
        time.sleep(1)  ### Delay for API calls
        indicator_in = indicator[0].strip()
        url = ("http://api.worldbank.org/v2/country/%s/indicator/%s?format=json" % (cc, indicator_in))
        r = requests.get(url = url)
        if r.status_code == 200:
            data_pull = r.json()
            data_pull = json.dumps(data_pull)
            data_pull = json.loads(data_pull)
            values_dict[indicator_in] = data_pull[1][10]['value']

        else:
            print(r.status_code)
            continue
        
    insert_statement = """INSERT INTO economic_2010 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict.items():
        count += 1
        if count < len(values_dict):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val

    cursor.execute(insert_statement)
    connection.commit()
    print(cc, " Economic Data input Complete")
    print("--- %s seconds ---" % (time.time() - start_time))   


    
    
print("Econ 2010 Database Complete")    
print("--- %s seconds ---" % (time.time() - start_time))    
    
# except (Exception, psycopg2.Error) as error :
#     print ("Error while fetching data from database", error)

# finally:
#     #closing database connection.
#     if(connection):
#         cursor.close()
#         connection.close()
#         print("Database connection is closed")

Fetching country codes
CC list created
Fetching Econ Indicator Codes
Indicator code list created
AFG  Economic Data input Complete
--- 34.07281970977783 seconds ---
400
ALB  Economic Data input Complete
--- 70.80333828926086 seconds ---
DZA  Economic Data input Complete
--- 108.24202799797058 seconds ---
ASM  Economic Data input Complete
--- 142.71297121047974 seconds ---
AND  Economic Data input Complete
--- 180.59252953529358 seconds ---
AGO  Economic Data input Complete
--- 218.00013208389282 seconds ---
ATG  Economic Data input Complete
--- 253.08284211158752 seconds ---
ARG  Economic Data input Complete
--- 290.31102418899536 seconds ---
ARM  Economic Data input Complete
--- 325.9591944217682 seconds ---
ABW  Economic Data input Complete
--- 362.6418116092682 seconds ---
AUS  Economic Data input Complete
--- 394.1649808883667 seconds ---

KeyboardInterrupt:

In [13]:
### Fill Economic Factors Tables 2010-2019 in Database
import requests
import json
import pandas as pd
import time

# try:
connection = psycopg2.connect(
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

cursor = connection.cursor()

countries_query = "select country_code from countries"
cursor.execute(countries_query)
print ("Fetching country codes")
countries = cursor.fetchall()

cc_list = []

for cc in countries:
    cc_list.append(cc[0])
print ("CC list created")

econ_indicator_query = "select indicator_code from econ_factors"
cursor.execute(econ_indicator_query)
print ("Fetching Econ Indicator Codes")
econ_indicators = cursor.fetchall()

econ_indicator_list = []
for indicator in econ_indicators:
    econ_indicator_list.append(indicator[0].strip())
print ("Indicator code list created")

start_time = time.time()
for cc in cc_list:
    
    ### As api calls time out, I don't want to repeat table entries, so checking if they exist and moving on if they do
    check_statement = 'select * from economic_2010 where "COUNTRY.CODE" =  ' + "'" + cc + "'"
    cursor.execute(check_statement)
    if bool(cursor.rowcount):
        continue
        
    values_dict_2010 = {'COUNTRY.CODE': cc}   ### dictionaries to hold values pulled from API
    values_dict_2011 = {'COUNTRY.CODE': cc}
    values_dict_2012 = {'COUNTRY.CODE': cc}   
    values_dict_2013 = {'COUNTRY.CODE': cc}   
    values_dict_2014 = {'COUNTRY.CODE': cc}   
    values_dict_2015 = {'COUNTRY.CODE': cc}   
    values_dict_2016 = {'COUNTRY.CODE': cc}   
    values_dict_2017 = {'COUNTRY.CODE': cc}   
    values_dict_2018 = {'COUNTRY.CODE': cc}   
    values_dict_2019 = {'COUNTRY.CODE': cc}     

    for indicator in econ_indicators:
        time.sleep(1)  ### Delay for API calls
        indicator_in = indicator[0].strip()
        url = ("http://api.worldbank.org/v2/country/%s/indicator/%s?format=json" % (cc, indicator_in))
        r = requests.get(url = url)
        if r.status_code == 200:
            data_pull = r.json()
            data_pull = json.dumps(data_pull)
            data_pull = json.loads(data_pull)
            
            ### years 2010 - 2019 correspond to indices 10 - 1, respectively
            values_dict_2010[indicator_in] = data_pull[1][10]['value']
            values_dict_2011[indicator_in] = data_pull[1][9]['value']
            values_dict_2012[indicator_in] = data_pull[1][8]['value']
            values_dict_2013[indicator_in] = data_pull[1][7]['value']
            values_dict_2014[indicator_in] = data_pull[1][6]['value']
            values_dict_2015[indicator_in] = data_pull[1][5]['value']
            values_dict_2016[indicator_in] = data_pull[1][4]['value']
            values_dict_2017[indicator_in] = data_pull[1][3]['value']
            values_dict_2018[indicator_in] = data_pull[1][2]['value']
            values_dict_2019[indicator_in] = data_pull[1][1]['value']

        else:
            print(r.status_code)
            continue
        
    
    ### 2010 Econ Data
    insert_statement = """INSERT INTO economic_2010 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2010.items():
        count += 1
        if count < len(values_dict_2010):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2011 Econ Data    
    insert_statement = """INSERT INTO economic_2011 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2011.items():
        count += 1
        if count < len(values_dict_2011):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2012 Econ Data
    insert_statement = """INSERT INTO economic_2012 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2012.items():
        count += 1
        if count < len(values_dict_2012):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2013 Econ Data
    insert_statement = """INSERT INTO economic_2013 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2013.items():
        count += 1
        if count < len(values_dict_2013):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2014 Econ Data    
    insert_statement = """INSERT INTO economic_2014 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2014.items():
        count += 1
        if count < len(values_dict_2014):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2015 Econ Data
    insert_statement = """INSERT INTO economic_2015 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2015.items():
        count += 1
        if count < len(values_dict_2015):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2016 Econ Data
    insert_statement = """INSERT INTO economic_2016 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2016.items():
        count += 1
        if count < len(values_dict_2016):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2017 Econ Data
    insert_statement = """INSERT INTO economic_2017 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2017.items():
        count += 1
        if count < len(values_dict_2017):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2018 Econ Data    
    insert_statement = """INSERT INTO economic_2018 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2018.items():
        count += 1
        if count < len(values_dict_2018):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2019 Econ Data
    insert_statement = """INSERT INTO economic_2019 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2019.items():
        count += 1
        if count < len(values_dict_2019):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    

    connection.commit()
    print(cc, " Economic Data input Complete")
    print("--- %s seconds ---" % (time.time() - start_time))   


    
    
print("Econ Tables Complete")    
print("--- %s seconds ---" % (time.time() - start_time))    
    
# except (Exception, psycopg2.Error) as error :
#     print ("Error while fetching data from database", error)

# finally:
#     #closing database connection.
#     if(connection):
#         cursor.close()
#         connection.close()
#         print("Database connection is closed")

Fetching country codes
CC list created
Fetching Econ Indicator Codes
Indicator code list created
AFG  Economic Data input Complete
--- 23.575249195098877 seconds ---
ALB  Economic Data input Complete
--- 46.79494857788086 seconds ---
DZA  Economic Data input Complete
--- 70.95076417922974 seconds ---
ASM  Economic Data input Complete
--- 97.53389716148376 seconds ---
AND  Economic Data input Complete
--- 121.58716201782227 seconds ---
AGO  Economic Data input Complete
--- 146.8801817893982 seconds ---
ATG  Economic Data input Complete
--- 169.18590784072876 seconds ---
ARG  Economic Data input Complete
--- 196.21045660972595 seconds ---
ARM  Economic Data input Complete
--- 222.37675738334656 seconds ---
ABW  Economic Data input Complete
--- 252.37744665145874 seconds ---
AUS  Economic Data input Complete
--- 277.17314863204956 seconds ---
AUT  Economic Data input Complete
--- 312.40082454681396 seconds ---
AZE  Economic Data input Complete
--- 352.9602882862091 seconds ---
BHS  Economic Data input Complete
--- 387.8642280101776 seconds ---
BHR  Economic Data input Complete
--- 421.8411400318146 seconds ---
BGD  Economic Data input Complete
--- 452.6861689090729 seconds ---
BRB  Economic Data input Complete
--- 487.53329491615295 seconds ---
BLR  Economic Data input Complete
--- 523.8070631027222 seconds ---
BEL  Economic Data input Complete
--- 556.3621799945831 seconds ---
BLZ  Economic Data input Complete
--- 588.2353625297546 seconds ---
BEN  Economic Data input Complete
--- 619.6233806610107 seconds ---
BMU  Economic Data input Complete
--- 656.4635543823242 seconds ---
BTN  Economic Data input Complete
--- 689.6841232776642 seconds ---
BOL  Economic Data input Complete
--- 722.8821022510529 seconds ---
BIH  Economic Data input Complete
--- 758.3343176841736 seconds ---
BWA  Economic Data input Complete
--- 788.2015631198883 seconds ---
BRA  Economic Data input Complete
--- 820.7486808300018 seconds ---
VGB  Economic Data input Complete
--- 857.7915177345276 seconds ---
BRN  Economic Data input Complete
--- 891.0440912246704 seconds ---
BGR  Economic Data input Complete
--- 923.0054104328156 seconds ---
BFA  Economic Data input Complete
--- 959.8377423286438 seconds ---
BDI  Economic Data input Complete
--- 997.338725566864 seconds ---
CPV  Economic Data input Complete
--- 1028.5298600196838 seconds ---
KHM  Economic Data input Complete
--- 1061.633369922638 seconds ---
CMR  Economic Data input Complete
--- 1089.0569865703583 seconds ---
CAN  Economic Data input Complete
--- 1118.6837270259857 seconds ---
CYM  Economic Data input Complete
--- 1151.55175614357 seconds ---
CAF  Economic Data input Complete
--- 1181.6084537506104 seconds ---
TCD  Economic Data input Complete
--- 1211.6459712982178 seconds ---
CHI  Economic Data input Complete
--- 1241.9947836399078 seconds ---
CHL  Economic Data input Complete
--- 1269.0673620700836 seconds ---
CHN  Economic Data input Complete
--- 1297.7968664169312 seconds ---
COL  Economic Data input Complete
--- 1323.045657634735 seconds ---
COM  Economic Data input Complete
--- 1350.2657985687256 seconds ---
COD  Economic Data input Complete
--- 1377.938555240631 seconds ---
COG  Economic Data input Complete
--- 1403.6921014785767 seconds ---
CRI  Economic Data input Complete
--- 1430.4565660953522 seconds ---
CIV  Economic Data input Complete
--- 1458.5100469589233 seconds ---
HRV  Economic Data input Complete
--- 1485.592407464981 seconds ---
CUB  Economic Data input Complete
--- 1512.4786417484283 seconds ---
CUW  Economic Data input Complete
--- 1534.266257762909 seconds ---
CYP  Economic Data input Complete
--- 1562.0394039154053 seconds ---
CZE  Economic Data input Complete
--- 1585.4343633651733 seconds ---
DNK  Economic Data input Complete
--- 1608.744703054428 seconds ---
DJI  Economic Data input Complete
--- 1633.7567451000214 seconds ---
DMA  Economic Data input Complete
--- 1672.0532915592194 seconds ---
DOM  Economic Data input Complete
--- 1712.7537469863892 seconds ---
ECU  Economic Data input Complete
--- 1744.4639065265656 seconds ---
EGY  Economic Data input Complete
--- 1776.1487545967102 seconds ---
SLV  Economic Data input Complete
--- 1810.560038805008 seconds ---
GNQ  Economic Data input Complete
--- 1847.109929561615 seconds ---
ERI  Economic Data input Complete
--- 1883.1051671504974 seconds ---
EST  Economic Data input Complete
--- 1922.3196585178375 seconds ---
SWZ  Economic Data input Complete
--- 1955.527901172638 seconds ---
ETH  Economic Data input Complete
--- 1987.4765410423279 seconds ---
FRO  Economic Data input Complete
--- 2021.0692014694214 seconds ---
FJI  Economic Data input Complete
--- 2050.79336643219 seconds ---
FIN  Economic Data input Complete
--- 2087.2234432697296 seconds ---
FRA  Economic Data input Complete
--- 2117.4802491664886 seconds ---
PYF  Economic Data input Complete
--- 2148.771668434143 seconds ---
GAB  Economic Data input Complete
--- 2180.008051633835 seconds ---
GMB  Economic Data input Complete
--- 2215.412388563156 seconds ---
GEO  Economic Data input Complete
--- 2250.122084379196 seconds ---
DEU  Economic Data input Complete
--- 2281.7763242721558 seconds ---
GHA  Economic Data input Complete
--- 2315.490313768387 seconds ---
GIB  Economic Data input Complete
--- 2345.93408036232 seconds ---
GRC  Economic Data input Complete
--- 2379.1289961338043 seconds ---
GRL  Economic Data input Complete
--- 2409.3024723529816 seconds ---
GRD  Economic Data input Complete
--- 2448.9623851776123 seconds ---
GUM  Economic Data input Complete
--- 2479.95561504364 seconds ---
GTM  Economic Data input Complete
--- 2513.945268392563 seconds ---
GIN  Economic Data input Complete
--- 2546.3812148571014 seconds ---
GNB  Economic Data input Complete
--- 2580.351784467697 seconds ---
GUY  Economic Data input Complete
--- 2617.1842200756073 seconds ---
HTI  Economic Data input Complete
--- 2652.5091774463654 seconds ---
HND  Economic Data input Complete
--- 2684.4221308231354 seconds ---
HKG  Economic Data input Complete
--- 2717.4452962875366 seconds ---
HUN  Economic Data input Complete
--- 2750.1007409095764 seconds ---
ISL  Economic Data input Complete
--- 2781.712309360504 seconds ---
IND  Economic Data input Complete
--- 2818.9850282669067 seconds ---
IDN  Economic Data input Complete
--- 2857.9277606010437 seconds ---
IRN  Economic Data input Complete
--- 2890.0023198127747 seconds ---
IRQ  Economic Data input Complete
--- 2924.567177772522 seconds ---
IRL  Economic Data input Complete
--- 2963.9822976589203 seconds ---
IMN  Economic Data input Complete
--- 3000.2555203437805 seconds ---
ISR  Economic Data input Complete
--- 3032.852688550949 seconds ---
ITA  Economic Data input Complete
--- 3064.931841135025 seconds ---
JAM  Economic Data input Complete
--- 3101.4373712539673 seconds ---
JPN  Economic Data input Complete
--- 3134.309492826462 seconds ---
JOR  Economic Data input Complete
--- 3210.8535022735596 seconds ---
KAZ  Economic Data input Complete
--- 3242.825023174286 seconds ---
KEN  Economic Data input Complete
--- 3281.4315724372864 seconds ---
KIR  Economic Data input Complete
--- 3312.897262573242 seconds ---
PRK  Economic Data input Complete
--- 3347.4219677448273 seconds ---
KOR  Economic Data input Complete
--- 3382.6116948127747 seconds ---
XKX  Economic Data input Complete
--- 3416.5926053524017 seconds ---
KWT  Economic Data input Complete
--- 3451.911535024643 seconds ---
KGZ  Economic Data input Complete
--- 3489.071445941925 seconds ---
LAO  Economic Data input Complete
--- 3525.094571828842 seconds ---
LVA  Economic Data input Complete
--- 3561.6426463127136 seconds ---
LBN  Economic Data input Complete
--- 3593.096774816513 seconds ---
LSO  Economic Data input Complete
--- 3626.2839329242706 seconds ---
LBR  Economic Data input Complete
--- 3663.6361696720123 seconds ---
LBY  Economic Data input Complete
--- 3700.5223093032837 seconds ---
LIE  Economic Data input Complete
--- 3738.1367032527924 seconds ---
LTU  Economic Data input Complete
--- 3775.607369661331 seconds ---
LUX  Economic Data input Complete
--- 3811.9825751781464 seconds ---
MAC  Economic Data input Complete
--- 3846.4797139167786 seconds ---
MDG  Economic Data input Complete
--- 3883.2694687843323 seconds ---

MWI  Economic Data input Complete
--- 3917.0050823688507 seconds ---
MYS  Economic Data input Complete
--- 3949.8971524238586 seconds ---
MDV  Economic Data input Complete
--- 3987.7966780662537 seconds ---
MLI  Economic Data input Complete
--- 4023.0683739185333 seconds ---
MLT  Economic Data input Complete
--- 4062.5622911453247 seconds ---
MHL  Economic Data input Complete
--- 4098.031220674515 seconds ---
MRT  Economic Data input Complete
--- 4135.730380535126 seconds ---
MUS  Economic Data input Complete
--- 4170.404089689255 seconds ---
MEX  Economic Data input Complete
--- 4205.189624547958 seconds ---
400
FSM  Economic Data input Complete
--- 4243.620266675949 seconds ---
MDA  Economic Data input Complete
--- 4282.376114368439 seconds ---
MCO  Economic Data input Complete
--- 4320.1906151771545 seconds ---
MNG  Economic Data input Complete
--- 4355.655956029892 seconds ---
MNE  Economic Data input Complete
--- 4392.3006048202515 seconds ---
MAR  Economic Data input Complete
--- 4426.105926990509 seconds ---
MOZ  Economic Data input Complete
--- 4465.3597638607025 seconds ---
MMR  Economic Data input Complete
--- 4503.690991640091 seconds ---
NAM  Economic Data input Complete
--- 4539.330374717712 seconds ---
NPL  Economic Data input Complete
--- 4575.252908706665 seconds ---
NLD  Economic Data input Complete
--- 4613.377205610275 seconds ---
NCL  Economic Data input Complete
--- 4652.435066699982 seconds ---
NZL  Economic Data input Complete
--- 4689.164990901947 seconds ---
NIC  Economic Data input Complete
--- 4727.858516931534 seconds ---
NER  Economic Data input Complete
--- 4766.035284042358 seconds ---
NGA  Economic Data input Complete
--- 4807.668960094452 seconds ---
400
MKD  Economic Data input Complete
--- 4839.988310337067 seconds ---
MNP  Economic Data input Complete
--- 4877.77606010437 seconds ---
NOR  Economic Data input Complete
--- 4912.796228170395 seconds ---
OMN  Economic Data input Complete
--- 4950.675369501114 seconds ---
PAK  Economic Data input Complete
--- 4991.880887508392 seconds ---
PLW  Economic Data input Complete
--- 5024.886859178543 seconds ---
PAN  Economic Data input Complete
--- 5056.133179187775 seconds ---
PNG  Economic Data input Complete
--- 5088.937436580658 seconds ---
PRY  Economic Data input Complete
--- 5123.441201448441 seconds ---
PER  Economic Data input Complete
--- 5156.558722019196 seconds ---
PHL  Economic Data input Complete
--- 5186.11737537384 seconds ---
POL  Economic Data input Complete
--- 5221.567065954208 seconds ---
PRT  Economic Data input Complete
--- 5252.222805976868 seconds ---
PRI  Economic Data input Complete
--- 5287.466963291168 seconds ---
QAT  Economic Data input Complete
--- 5319.031699419022 seconds ---
ROU  Economic Data input Complete
--- 5349.688921689987 seconds ---
RUS  Economic Data input Complete
--- 5384.60816526413 seconds ---
RWA  Economic Data input Complete
--- 5418.945860385895 seconds ---
WSM  Economic Data input Complete
--- 5455.025387763977 seconds ---
SMR  Economic Data input Complete
--- 5487.614610671997 seconds ---
STP  Economic Data input Complete
--- 5518.936854362488 seconds ---
SAU  Economic Data input Complete
--- 5549.929112434387 seconds ---
SEN  Economic Data input Complete
--- 5581.365067720413 seconds ---
SRB  Economic Data input Complete
--- 5616.962091445923 seconds ---
SYC  Economic Data input Complete
--- 5662.073960781097 seconds ---
SLE  Economic Data input Complete
--- 5695.364885568619 seconds ---
400
SGP  Economic Data input Complete
--- 5739.127925872803 seconds ---
SXM  Economic Data input Complete
--- 5777.135021209717 seconds ---
SVK  Economic Data input Complete
--- 5815.362457990646 seconds ---
SVN  Economic Data input Complete
--- 5850.736453533173 seconds ---
SLB  Economic Data input Complete
--- 5887.266633033752 seconds ---
SOM  Economic Data input Complete
--- 5925.53161406517 seconds ---
ZAF  Economic Data input Complete
--- 5962.586855649948 seconds ---
SSD  Economic Data input Complete
--- 5996.672824382782 seconds ---
ESP  Economic Data input Complete
--- 6037.632858991623 seconds ---
LKA  Economic Data input Complete
--- 6099.786039113998 seconds ---
KNA  Economic Data input Complete
--- 6132.550842761993 seconds ---
LCA  Economic Data input Complete
--- 6167.1338794231415 seconds ---
MAF  Economic Data input Complete
--- 6199.391247987747 seconds ---
VCT  Economic Data input Complete
--- 6233.710458517075 seconds ---
SDN  Economic Data input Complete
--- 6267.397399425507 seconds ---
SUR  Economic Data input Complete
--- 6301.789248466492 seconds ---
SWE  Economic Data input Complete
--- 6339.885422468185 seconds ---
CHE  Economic Data input Complete
--- 6378.891953229904 seconds ---
SYR  Economic Data input Complete
--- 6417.513308048248 seconds ---
TJK  Economic Data input Complete
--- 6451.434075117111 seconds ---
TZA  Economic Data input Complete
--- 6485.012385129929 seconds ---
THA  Economic Data input Complete
--- 6518.580597400665 seconds ---
TLS  Economic Data input Complete
--- 6552.604689836502 seconds ---
TGO  Economic Data input Complete
--- 6586.448118925095 seconds ---
TON  Economic Data input Complete
--- 6618.129061937332 seconds ---
TTO  Economic Data input Complete
--- 6649.372977018356 seconds ---
TUN  Economic Data input Complete
--- 6679.885994672775 seconds ---
400
TUR  Economic Data input Complete
--- 6737.770505189896 seconds ---
TKM  Economic Data input Complete
--- 6771.3974549770355 seconds ---
TCA  Economic Data input Complete
--- 6806.051943540573 seconds ---
TUV  Economic Data input Complete
--- 6842.458060979843 seconds ---
UGA  Economic Data input Complete
--- 6879.309424877167 seconds ---
UKR  Economic Data input Complete
--- 6916.039123535156 seconds ---
ARE  Economic Data input Complete
--- 6951.729944705963 seconds ---
GBR  Economic Data input Complete
--- 6988.3726541996 seconds ---
USA  Economic Data input Complete
--- 7026.230840682983 seconds ---
URY  Economic Data input Complete
--- 7061.698077440262 seconds ---
UZB  Economic Data input Complete
--- 7097.510453462601 seconds ---
VUT  Economic Data input Complete
--- 7134.915424823761 seconds ---
VEN  Economic Data input Complete
--- 7170.6819360256195 seconds ---
VNM  Economic Data input Complete
--- 7203.347138643265 seconds ---
VIR  Economic Data input Complete
--- 7239.218963623047 seconds ---
PSE  Economic Data input Complete
--- 7275.497928619385 seconds ---
YEM  Economic Data input Complete
--- 7320.4866988658905 seconds ---
ZMB  Economic Data input Complete
--- 7357.522523641586 seconds ---
ZWE  Economic Data input Complete
--- 7392.47868180275 seconds ---
Econ Tables Complete
--- 7392.479679107666 seconds ---

In [14]:
### Create SQL tables to store WorldBank Social data by year pulled from API

conn = psycopg2.connect (
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

conn.autocommit = True

cursor = conn.cursor()

insert_statement_10 = 'DROP TABLE IF EXISTS social_2010; CREATE TABLE social_2010("COUNTRY.CODE" CHAR(3),'
insert_statement_11 = 'DROP TABLE IF EXISTS social_2011; CREATE TABLE social_2011("COUNTRY.CODE" CHAR(3),'
insert_statement_12 = 'DROP TABLE IF EXISTS social_2012; CREATE TABLE social_2012("COUNTRY.CODE" CHAR(3),'
insert_statement_13 = 'DROP TABLE IF EXISTS social_2013; CREATE TABLE social_2013("COUNTRY.CODE" CHAR(3),'
insert_statement_14 = 'DROP TABLE IF EXISTS social_2014; CREATE TABLE social_2014("COUNTRY.CODE" CHAR(3),'
insert_statement_15 = 'DROP TABLE IF EXISTS social_2015; CREATE TABLE social_2015("COUNTRY.CODE" CHAR(3),'
insert_statement_16 = 'DROP TABLE IF EXISTS social_2016; CREATE TABLE social_2016("COUNTRY.CODE" CHAR(3),'
insert_statement_17 = 'DROP TABLE IF EXISTS social_2017; CREATE TABLE social_2017("COUNTRY.CODE" CHAR(3),'
insert_statement_18 = 'DROP TABLE IF EXISTS social_2018; CREATE TABLE social_2018("COUNTRY.CODE" CHAR(3),'
insert_statement_19 = 'DROP TABLE IF EXISTS social_2019; CREATE TABLE social_2019("COUNTRY.CODE" CHAR(3),'

count = 0
column_headers = ""
for key in social_dict.keys():
    column_headers = column_headers + '"' + key + '"' + " CHAR(255)"
    count += 1
    if count < len(social_dict):
        column_headers = column_headers + ", "
        column_headers
    else:
        column_headers = column_headers + ");"
        column_headers

insert_statement_10 = insert_statement_10 + column_headers
insert_statement_11 = insert_statement_11 + column_headers
insert_statement_12 = insert_statement_12 + column_headers
insert_statement_13 = insert_statement_13 + column_headers
insert_statement_14 = insert_statement_14 + column_headers
insert_statement_15 = insert_statement_15 + column_headers
insert_statement_16 = insert_statement_16 + column_headers
insert_statement_17 = insert_statement_17 + column_headers
insert_statement_18 = insert_statement_18 + column_headers
insert_statement_19 = insert_statement_19 + column_headers

cursor.execute(insert_statement_10)
cursor.execute(insert_statement_11)
cursor.execute(insert_statement_12)
cursor.execute(insert_statement_13)
cursor.execute(insert_statement_14)
cursor.execute(insert_statement_15)
cursor.execute(insert_statement_16)
cursor.execute(insert_statement_17)
cursor.execute(insert_statement_18)
cursor.execute(insert_statement_19)

print("Social tables created successfully.......")

conn.close()

Social tables created successfully.......

In [15]:
### Create SQL tables to store WorldBank Health data by year pulled from API

conn = psycopg2.connect (
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

conn.autocommit = True

cursor = conn.cursor()

insert_statement_10 = 'DROP TABLE IF EXISTS health_2010; CREATE TABLE health_2010("COUNTRY.CODE" CHAR(3),'
insert_statement_11 = 'DROP TABLE IF EXISTS health_2011; CREATE TABLE health_2011("COUNTRY.CODE" CHAR(3),'
insert_statement_12 = 'DROP TABLE IF EXISTS health_2012; CREATE TABLE health_2012("COUNTRY.CODE" CHAR(3),'
insert_statement_13 = 'DROP TABLE IF EXISTS health_2013; CREATE TABLE health_2013("COUNTRY.CODE" CHAR(3),'
insert_statement_14 = 'DROP TABLE IF EXISTS health_2014; CREATE TABLE health_2014("COUNTRY.CODE" CHAR(3),'
insert_statement_15 = 'DROP TABLE IF EXISTS health_2015; CREATE TABLE health_2015("COUNTRY.CODE" CHAR(3),'
insert_statement_16 = 'DROP TABLE IF EXISTS health_2016; CREATE TABLE health_2016("COUNTRY.CODE" CHAR(3),'
insert_statement_17 = 'DROP TABLE IF EXISTS health_2017; CREATE TABLE health_2017("COUNTRY.CODE" CHAR(3),'
insert_statement_18 = 'DROP TABLE IF EXISTS health_2018; CREATE TABLE health_2018("COUNTRY.CODE" CHAR(3),'
insert_statement_19 = 'DROP TABLE IF EXISTS health_2019; CREATE TABLE health_2019("COUNTRY.CODE" CHAR(3),'

count = 0
column_headers = ""
for key in health_dict.keys():
    column_headers = column_headers + '"' + key + '"' + " CHAR(255)"
    count += 1
    if count < len(health_dict):
        column_headers = column_headers + ", "
        column_headers
    else:
        column_headers = column_headers + ");"
        column_headers

insert_statement_10 = insert_statement_10 + column_headers
insert_statement_11 = insert_statement_11 + column_headers
insert_statement_12 = insert_statement_12 + column_headers
insert_statement_13 = insert_statement_13 + column_headers
insert_statement_14 = insert_statement_14 + column_headers
insert_statement_15 = insert_statement_15 + column_headers
insert_statement_16 = insert_statement_16 + column_headers
insert_statement_17 = insert_statement_17 + column_headers
insert_statement_18 = insert_statement_18 + column_headers
insert_statement_19 = insert_statement_19 + column_headers

cursor.execute(insert_statement_10)
cursor.execute(insert_statement_11)
cursor.execute(insert_statement_12)
cursor.execute(insert_statement_13)
cursor.execute(insert_statement_14)
cursor.execute(insert_statement_15)
cursor.execute(insert_statement_16)
cursor.execute(insert_statement_17)
cursor.execute(insert_statement_18)
cursor.execute(insert_statement_19)

print("Health tables created successfully.......")

conn.close()

Health tables created successfully.......

In [16]:
### Create SQL tables to store WorldBank Education data by year pulled from API

conn = psycopg2.connect (
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

conn.autocommit = True

cursor = conn.cursor()

insert_statement_10 = 'DROP TABLE IF EXISTS education_2010; CREATE TABLE education_2010("COUNTRY.CODE" CHAR(3),'
insert_statement_11 = 'DROP TABLE IF EXISTS education_2011; CREATE TABLE education_2011("COUNTRY.CODE" CHAR(3),'
insert_statement_12 = 'DROP TABLE IF EXISTS education_2012; CREATE TABLE education_2012("COUNTRY.CODE" CHAR(3),'
insert_statement_13 = 'DROP TABLE IF EXISTS education_2013; CREATE TABLE education_2013("COUNTRY.CODE" CHAR(3),'
insert_statement_14 = 'DROP TABLE IF EXISTS education_2014; CREATE TABLE education_2014("COUNTRY.CODE" CHAR(3),'
insert_statement_15 = 'DROP TABLE IF EXISTS education_2015; CREATE TABLE education_2015("COUNTRY.CODE" CHAR(3),'
insert_statement_16 = 'DROP TABLE IF EXISTS education_2016; CREATE TABLE education_2016("COUNTRY.CODE" CHAR(3),'
insert_statement_17 = 'DROP TABLE IF EXISTS education_2017; CREATE TABLE education_2017("COUNTRY.CODE" CHAR(3),'
insert_statement_18 = 'DROP TABLE IF EXISTS education_2018; CREATE TABLE education_2018("COUNTRY.CODE" CHAR(3),'
insert_statement_19 = 'DROP TABLE IF EXISTS education_2019; CREATE TABLE education_2019("COUNTRY.CODE" CHAR(3),'

count = 0
column_headers = ""
for key in education_dict.keys():
    column_headers = column_headers + '"' + key + '"' + " CHAR(255)"
    count += 1
    if count < len(education_dict):
        column_headers = column_headers + ", "
        column_headers
    else:
        column_headers = column_headers + ");"
        column_headers

insert_statement_10 = insert_statement_10 + column_headers
insert_statement_11 = insert_statement_11 + column_headers
insert_statement_12 = insert_statement_12 + column_headers
insert_statement_13 = insert_statement_13 + column_headers
insert_statement_14 = insert_statement_14 + column_headers
insert_statement_15 = insert_statement_15 + column_headers
insert_statement_16 = insert_statement_16 + column_headers
insert_statement_17 = insert_statement_17 + column_headers
insert_statement_18 = insert_statement_18 + column_headers
insert_statement_19 = insert_statement_19 + column_headers

cursor.execute(insert_statement_10)
cursor.execute(insert_statement_11)
cursor.execute(insert_statement_12)
cursor.execute(insert_statement_13)
cursor.execute(insert_statement_14)
cursor.execute(insert_statement_15)
cursor.execute(insert_statement_16)
cursor.execute(insert_statement_17)
cursor.execute(insert_statement_18)
cursor.execute(insert_statement_19)

print("Education tables created successfully.......")

conn.close()

Education tables created successfully.......

In [17]:
### Create SQL tables to store WorldBank Infrastructure data by year pulled from API

conn = psycopg2.connect (
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

conn.autocommit = True

cursor = conn.cursor()

insert_statement_10 = 'DROP TABLE IF EXISTS infra_2010; CREATE TABLE infra_2010("COUNTRY.CODE" CHAR(3),'
insert_statement_11 = 'DROP TABLE IF EXISTS infra_2011; CREATE TABLE infra_2011("COUNTRY.CODE" CHAR(3),'
insert_statement_12 = 'DROP TABLE IF EXISTS infra_2012; CREATE TABLE infra_2012("COUNTRY.CODE" CHAR(3),'
insert_statement_13 = 'DROP TABLE IF EXISTS infra_2013; CREATE TABLE infra_2013("COUNTRY.CODE" CHAR(3),'
insert_statement_14 = 'DROP TABLE IF EXISTS infra_2014; CREATE TABLE infra_2014("COUNTRY.CODE" CHAR(3),'
insert_statement_15 = 'DROP TABLE IF EXISTS infra_2015; CREATE TABLE infra_2015("COUNTRY.CODE" CHAR(3),'
insert_statement_16 = 'DROP TABLE IF EXISTS infra_2016; CREATE TABLE infra_2016("COUNTRY.CODE" CHAR(3),'
insert_statement_17 = 'DROP TABLE IF EXISTS infra_2017; CREATE TABLE infra_2017("COUNTRY.CODE" CHAR(3),'
insert_statement_18 = 'DROP TABLE IF EXISTS infra_2018; CREATE TABLE infra_2018("COUNTRY.CODE" CHAR(3),'
insert_statement_19 = 'DROP TABLE IF EXISTS infra_2019; CREATE TABLE infra_2019("COUNTRY.CODE" CHAR(3),'

count = 0
column_headers = ""
for key in infra_dict.keys():
    column_headers = column_headers + '"' + key + '"' + " CHAR(255)"
    count += 1
    if count < len(infra_dict):
        column_headers = column_headers + ", "
        column_headers
    else:
        column_headers = column_headers + ");"
        column_headers

insert_statement_10 = insert_statement_10 + column_headers
insert_statement_11 = insert_statement_11 + column_headers
insert_statement_12 = insert_statement_12 + column_headers
insert_statement_13 = insert_statement_13 + column_headers
insert_statement_14 = insert_statement_14 + column_headers
insert_statement_15 = insert_statement_15 + column_headers
insert_statement_16 = insert_statement_16 + column_headers
insert_statement_17 = insert_statement_17 + column_headers
insert_statement_18 = insert_statement_18 + column_headers
insert_statement_19 = insert_statement_19 + column_headers

cursor.execute(insert_statement_10)
cursor.execute(insert_statement_11)
cursor.execute(insert_statement_12)
cursor.execute(insert_statement_13)
cursor.execute(insert_statement_14)
cursor.execute(insert_statement_15)
cursor.execute(insert_statement_16)
cursor.execute(insert_statement_17)
cursor.execute(insert_statement_18)
cursor.execute(insert_statement_19)

print("Infrastructure tables created successfully.......")

conn.close()

Infrastructure tables created successfully.......

In [18]:
### Create SQL tables to store WorldBank Other data by year pulled from API

conn = psycopg2.connect (
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

conn.autocommit = True

cursor = conn.cursor()

insert_statement_10 = 'DROP TABLE IF EXISTS other_2010; CREATE TABLE other_2010("COUNTRY.CODE" CHAR(3),'
insert_statement_11 = 'DROP TABLE IF EXISTS other_2011; CREATE TABLE other_2011("COUNTRY.CODE" CHAR(3),'
insert_statement_12 = 'DROP TABLE IF EXISTS other_2012; CREATE TABLE other_2012("COUNTRY.CODE" CHAR(3),'
insert_statement_13 = 'DROP TABLE IF EXISTS other_2013; CREATE TABLE other_2013("COUNTRY.CODE" CHAR(3),'
insert_statement_14 = 'DROP TABLE IF EXISTS other_2014; CREATE TABLE other_2014("COUNTRY.CODE" CHAR(3),'
insert_statement_15 = 'DROP TABLE IF EXISTS other_2015; CREATE TABLE other_2015("COUNTRY.CODE" CHAR(3),'
insert_statement_16 = 'DROP TABLE IF EXISTS other_2016; CREATE TABLE other_2016("COUNTRY.CODE" CHAR(3),'
insert_statement_17 = 'DROP TABLE IF EXISTS other_2017; CREATE TABLE other_2017("COUNTRY.CODE" CHAR(3),'
insert_statement_18 = 'DROP TABLE IF EXISTS other_2018; CREATE TABLE other_2018("COUNTRY.CODE" CHAR(3),'
insert_statement_19 = 'DROP TABLE IF EXISTS other_2019; CREATE TABLE other_2019("COUNTRY.CODE" CHAR(3),'

count = 0
column_headers = ""
for key in other_dict.keys():
    column_headers = column_headers + '"' + key + '"' + " CHAR(255)"
    count += 1
    if count < len(other_dict):
        column_headers = column_headers + ", "
        column_headers
    else:
        column_headers = column_headers + ");"
        column_headers

insert_statement_10 = insert_statement_10 + column_headers
insert_statement_11 = insert_statement_11 + column_headers
insert_statement_12 = insert_statement_12 + column_headers
insert_statement_13 = insert_statement_13 + column_headers
insert_statement_14 = insert_statement_14 + column_headers
insert_statement_15 = insert_statement_15 + column_headers
insert_statement_16 = insert_statement_16 + column_headers
insert_statement_17 = insert_statement_17 + column_headers
insert_statement_18 = insert_statement_18 + column_headers
insert_statement_19 = insert_statement_19 + column_headers

cursor.execute(insert_statement_10)
cursor.execute(insert_statement_11)
cursor.execute(insert_statement_12)
cursor.execute(insert_statement_13)
cursor.execute(insert_statement_14)
cursor.execute(insert_statement_15)
cursor.execute(insert_statement_16)
cursor.execute(insert_statement_17)
cursor.execute(insert_statement_18)
cursor.execute(insert_statement_19)

print("Other tables created successfully.......")

conn.close()

Other tables created successfully.......

In [20]:
### Fill Social Factors Tables 2010-2019 in Database
import requests
import json
import pandas as pd
import time

# try:
connection = psycopg2.connect(
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

cursor = connection.cursor()

countries_query = "select country_code from countries"
cursor.execute(countries_query)
print ("Fetching country codes")
countries = cursor.fetchall()

cc_list = []

for cc in countries:
    cc_list.append(cc[0])
print ("CC list created")

social_indicator_query = "select indicator_code from social_factors"
cursor.execute(social_indicator_query)
print ("Fetching Social Indicator Codes")
social_indicators = cursor.fetchall()

social_indicator_list = []
for indicator in social_indicators:
    social_indicator_list.append(indicator[0].strip())
print ("Indicator code list created")

start_time = time.time()
for cc in cc_list:
    
    ### If api calls time out, I don't want to repeat table entries, so checking if they exist and moving on if they do
    check_statement = 'select * from social_2019 where "COUNTRY.CODE" =  ' + "'" + cc + "'"
    cursor.execute(check_statement)
    if bool(cursor.rowcount):
        continue
        
    values_dict_2010 = {'COUNTRY.CODE': cc}   ### dictionaries to hold values pulled from API
    values_dict_2011 = {'COUNTRY.CODE': cc}
    values_dict_2012 = {'COUNTRY.CODE': cc}   
    values_dict_2013 = {'COUNTRY.CODE': cc}   
    values_dict_2014 = {'COUNTRY.CODE': cc}   
    values_dict_2015 = {'COUNTRY.CODE': cc}   
    values_dict_2016 = {'COUNTRY.CODE': cc}   
    values_dict_2017 = {'COUNTRY.CODE': cc}   
    values_dict_2018 = {'COUNTRY.CODE': cc}   
    values_dict_2019 = {'COUNTRY.CODE': cc}     

    for indicator in social_indicators:
        time.sleep(1)  ### Delay for API calls
        indicator_in = indicator[0].strip()
        url = ("http://api.worldbank.org/v2/country/%s/indicator/%s?format=json" % (cc, indicator_in))
        r = requests.get(url = url)
        if r.status_code == 200:
            data_pull = r.json()
            data_pull = json.dumps(data_pull)
            data_pull = json.loads(data_pull)
            
            ### years 2010 - 2019 correspond to indices 10 - 1, respectively
            values_dict_2010[indicator_in] = data_pull[1][10]['value']
            values_dict_2011[indicator_in] = data_pull[1][9]['value']
            values_dict_2012[indicator_in] = data_pull[1][8]['value']
            values_dict_2013[indicator_in] = data_pull[1][7]['value']
            values_dict_2014[indicator_in] = data_pull[1][6]['value']
            values_dict_2015[indicator_in] = data_pull[1][5]['value']
            values_dict_2016[indicator_in] = data_pull[1][4]['value']
            values_dict_2017[indicator_in] = data_pull[1][3]['value']
            values_dict_2018[indicator_in] = data_pull[1][2]['value']
            values_dict_2019[indicator_in] = data_pull[1][1]['value']

        else:
            print(r.status_code)
            continue
        
    
    ### 2010 Social Data
    insert_statement = """INSERT INTO social_2010 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2010.items():
        count += 1
        if count < len(values_dict_2010):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2011 Social Data    
    insert_statement = """INSERT INTO social_2011 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2011.items():
        count += 1
        if count < len(values_dict_2011):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2012 Social Data
    insert_statement = """INSERT INTO social_2012 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2012.items():
        count += 1
        if count < len(values_dict_2012):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2013 Social Data
    insert_statement = """INSERT INTO social_2013 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2013.items():
        count += 1
        if count < len(values_dict_2013):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2014 Social Data    
    insert_statement = """INSERT INTO social_2014 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2014.items():
        count += 1
        if count < len(values_dict_2014):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2015 Social Data
    insert_statement = """INSERT INTO social_2015 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2015.items():
        count += 1
        if count < len(values_dict_2015):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2016 Social Data
    insert_statement = """INSERT INTO social_2016 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2016.items():
        count += 1
        if count < len(values_dict_2016):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2017 Social Data
    insert_statement = """INSERT INTO social_2017 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2017.items():
        count += 1
        if count < len(values_dict_2017):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2018 Social Data    
    insert_statement = """INSERT INTO social_2018 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2018.items():
        count += 1
        if count < len(values_dict_2018):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2019 Social Data
    insert_statement = """INSERT INTO social_2019 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2019.items():
        count += 1
        if count < len(values_dict_2019):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    

    connection.commit()
    print(cc, " Social Data input Complete")
    print("--- %s seconds ---" % (time.time() - start_time))   


    
    
print("Social Tables Complete")    
print("--- %s seconds ---" % (time.time() - start_time))    
    
# except (Exception, psycopg2.Error) as error :
#     print ("Error while fetching data from database", error)

# finally:
#     #closing database connection.
#     if(connection):
#         cursor.close()
#         connection.close()
#         print("Database connection is closed")

Fetching country codes
CC list created
Fetching Social Indicator Codes
Indicator code list created
MCO  Social Data input Complete
--- 21.09476590156555 seconds ---
MNG  Social Data input Complete
--- 42.64297127723694 seconds ---
MNE  Social Data input Complete
--- 58.679524660110474 seconds ---
MAR  Social Data input Complete
--- 81.61828589439392 seconds ---
MOZ  Social Data input Complete
--- 100.64918637275696 seconds ---
MMR  Social Data input Complete
--- 118.47666263580322 seconds ---
NAM  Social Data input Complete
--- 144.93593168258667 seconds ---
NPL  Social Data input Complete
--- 167.67913937568665 seconds ---
NLD  Social Data input Complete
--- 184.3721776008606 seconds ---
NCL  Social Data input Complete
--- 205.07353973388672 seconds ---
NZL  Social Data input Complete
--- 222.99206399917603 seconds ---
NIC  Social Data input Complete
--- 240.4018428325653 seconds ---
NER  Social Data input Complete
--- 259.0691113471985 seconds ---
NGA  Social Data input Complete
--- 275.9858329296112 seconds ---
MKD  Social Data input Complete
--- 294.3837742805481 seconds ---
MNP  Social Data input Complete
--- 312.4537777900696 seconds ---
NOR  Social Data input Complete
--- 333.51806902885437 seconds ---
OMN  Social Data input Complete
--- 351.38315081596375 seconds ---
PAK  Social Data input Complete
--- 368.86377024650574 seconds ---
PLW  Social Data input Complete
--- 386.8530943393707 seconds ---
PAN  Social Data input Complete
--- 405.72237181663513 seconds ---
PNG  Social Data input Complete
--- 421.6810121536255 seconds ---
PRY  Social Data input Complete
--- 441.116512298584 seconds ---
PER  Social Data input Complete
--- 458.13172030448914 seconds ---
PHL  Social Data input Complete
--- 474.364554643631 seconds ---
POL  Social Data input Complete
--- 493.3520007133484 seconds ---
PRT  Social Data input Complete
--- 514.9920768737793 seconds ---
PRI  Social Data input Complete
--- 533.9445557594299 seconds ---
QAT  Social Data input Complete
--- 553.1317708492279 seconds ---
ROU  Social Data input Complete
--- 572.3312041759491 seconds ---
RUS  Social Data input Complete
--- 591.0653195381165 seconds ---
RWA  Social Data input Complete
--- 610.1493680477142 seconds ---
WSM  Social Data input Complete
--- 630.6930141448975 seconds ---
SMR  Social Data input Complete
--- 650.1859011650085 seconds ---
STP  Social Data input Complete
--- 670.5371606349945 seconds ---
SAU  Social Data input Complete
--- 687.9873280525208 seconds ---
SEN  Social Data input Complete
--- 711.0918312072754 seconds ---
SRB  Social Data input Complete
--- 735.0382487773895 seconds ---
SYC  Social Data input Complete
--- 753.1034996509552 seconds ---
SLE  Social Data input Complete
--- 769.450516462326 seconds ---
SGP  Social Data input Complete
--- 786.1391251087189 seconds ---
SXM  Social Data input Complete
--- 802.9700453281403 seconds ---
SVK  Social Data input Complete
--- 820.4901907444 seconds ---
SVN  Social Data input Complete
--- 838.3278667926788 seconds ---
SLB  Social Data input Complete
--- 856.8673007488251 seconds ---
SOM  Social Data input Complete
--- 873.777265548706 seconds ---
ZAF  Social Data input Complete
--- 892.250951051712 seconds ---
SSD  Social Data input Complete
--- 910.9091875553131 seconds ---
ESP  Social Data input Complete
--- 930.4085831642151 seconds ---
LKA  Social Data input Complete
--- 948.558865070343 seconds ---
KNA  Social Data input Complete
--- 967.1415705680847 seconds ---
LCA  Social Data input Complete
--- 985.4400436878204 seconds ---
MAF  Social Data input Complete
--- 1007.7643508911133 seconds ---
VCT  Social Data input Complete
--- 1026.140280008316 seconds ---
SDN  Social Data input Complete
--- 1046.299144268036 seconds ---
SUR  Social Data input Complete
--- 1064.131602048874 seconds ---
SWE  Social Data input Complete
--- 1084.0670733451843 seconds ---
CHE  Social Data input Complete
--- 1105.1726307868958 seconds ---
SYR  Social Data input Complete
--- 1124.9733107089996 seconds ---
TJK  Social Data input Complete
--- 1141.1331436634064 seconds ---
TZA  Social Data input Complete
--- 1160.2662234306335 seconds ---
THA  Social Data input Complete
--- 1179.9263882637024 seconds ---
TLS  Social Data input Complete
--- 1195.1685440540314 seconds ---
TGO  Social Data input Complete
--- 1214.9492700099945 seconds ---
400
TON  Social Data input Complete
--- 1231.4480950832367 seconds ---
TTO  Social Data input Complete
--- 1251.1309881210327 seconds ---
TUN  Social Data input Complete
--- 1271.9332630634308 seconds ---
TUR  Social Data input Complete
--- 1292.6486101150513 seconds ---
TKM  Social Data input Complete
--- 1311.0126123428345 seconds ---
TCA  Social Data input Complete
--- 1328.7871990203857 seconds ---
TUV  Social Data input Complete
--- 1346.3934035301208 seconds ---
UGA  Social Data input Complete
--- 1364.0863194465637 seconds ---
UKR  Social Data input Complete
--- 1382.471572637558 seconds ---
ARE  Social Data input Complete
--- 1400.194997549057 seconds ---
GBR  Social Data input Complete
--- 1416.9717299938202 seconds ---
USA  Social Data input Complete
--- 1435.2980434894562 seconds ---
URY  Social Data input Complete
--- 1451.2993483543396 seconds ---
UZB  Social Data input Complete
--- 1471.3490235805511 seconds ---
VUT  Social Data input Complete
--- 1488.4678740501404 seconds ---
400
VEN  Social Data input Complete
--- 1506.4311401844025 seconds ---
VNM  Social Data input Complete
--- 1524.283120393753 seconds ---
VIR  Social Data input Complete
--- 1543.558536529541 seconds ---
PSE  Social Data input Complete
--- 1561.1323940753937 seconds ---
YEM  Social Data input Complete
--- 1577.9439630508423 seconds ---
ZMB  Social Data input Complete
--- 1595.1656968593597 seconds ---
ZWE  Social Data input Complete
--- 1613.0969367027283 seconds ---
Social Tables Complete
--- 1613.0969367027283 seconds ---

In [21]:
### Fill Health Factors Tables 2010-2019 in Database
import requests
import json
import pandas as pd
import time

# try:
connection = psycopg2.connect(
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

cursor = connection.cursor()

countries_query = "select country_code from countries"
cursor.execute(countries_query)
print ("Fetching country codes")
countries = cursor.fetchall()

cc_list = []

for cc in countries:
    cc_list.append(cc[0])
print ("CC list created")

health_indicator_query = "select indicator_code from health_factors"
cursor.execute(health_indicator_query)
print ("Fetching Health Indicator Codes")
health_indicators = cursor.fetchall()

health_indicator_list = []
for indicator in health_indicators:
    health_indicator_list.append(indicator[0].strip())
print ("Indicator code list created")

start_time = time.time()
for cc in cc_list:
    
    ### If api calls time out, I don't want to repeat table entries, so checking if they exist and moving on if they do
    check_statement = 'select * from health_2019 where "COUNTRY.CODE" =  ' + "'" + cc + "'"
    cursor.execute(check_statement)
    if bool(cursor.rowcount):
        continue
        
    values_dict_2010 = {'COUNTRY.CODE': cc}   ### dictionaries to hold values pulled from API
    values_dict_2011 = {'COUNTRY.CODE': cc}
    values_dict_2012 = {'COUNTRY.CODE': cc}   
    values_dict_2013 = {'COUNTRY.CODE': cc}   
    values_dict_2014 = {'COUNTRY.CODE': cc}   
    values_dict_2015 = {'COUNTRY.CODE': cc}   
    values_dict_2016 = {'COUNTRY.CODE': cc}   
    values_dict_2017 = {'COUNTRY.CODE': cc}   
    values_dict_2018 = {'COUNTRY.CODE': cc}   
    values_dict_2019 = {'COUNTRY.CODE': cc}     

    for indicator in health_indicators:
        time.sleep(1)  ### Delay for API calls
        indicator_in = indicator[0].strip()
        url = ("http://api.worldbank.org/v2/country/%s/indicator/%s?format=json" % (cc, indicator_in))
        r = requests.get(url = url)
        if r.status_code == 200:
            data_pull = r.json()
            data_pull = json.dumps(data_pull)
            data_pull = json.loads(data_pull)
            
            ### years 2010 - 2019 correspond to indices 10 - 1, respectively
            values_dict_2010[indicator_in] = data_pull[1][10]['value']
            values_dict_2011[indicator_in] = data_pull[1][9]['value']
            values_dict_2012[indicator_in] = data_pull[1][8]['value']
            values_dict_2013[indicator_in] = data_pull[1][7]['value']
            values_dict_2014[indicator_in] = data_pull[1][6]['value']
            values_dict_2015[indicator_in] = data_pull[1][5]['value']
            values_dict_2016[indicator_in] = data_pull[1][4]['value']
            values_dict_2017[indicator_in] = data_pull[1][3]['value']
            values_dict_2018[indicator_in] = data_pull[1][2]['value']
            values_dict_2019[indicator_in] = data_pull[1][1]['value']

        else:
            print(r.status_code)
            continue
        
    
    ### 2010 Health Data
    insert_statement = """INSERT INTO health_2010 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2010.items():
        count += 1
        if count < len(values_dict_2010):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2011 Health Data    
    insert_statement = """INSERT INTO health_2011 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2011.items():
        count += 1
        if count < len(values_dict_2011):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2012 Health Data
    insert_statement = """INSERT INTO health_2012 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2012.items():
        count += 1
        if count < len(values_dict_2012):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2013 Health Data
    insert_statement = """INSERT INTO health_2013 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2013.items():
        count += 1
        if count < len(values_dict_2013):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2014 Health Data    
    insert_statement = """INSERT INTO health_2014 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2014.items():
        count += 1
        if count < len(values_dict_2014):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2015 Health Data
    insert_statement = """INSERT INTO health_2015 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2015.items():
        count += 1
        if count < len(values_dict_2015):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2016 Health Data
    insert_statement = """INSERT INTO health_2016 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2016.items():
        count += 1
        if count < len(values_dict_2016):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2017 Health Data
    insert_statement = """INSERT INTO health_2017 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2017.items():
        count += 1
        if count < len(values_dict_2017):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2018 Health Data    
    insert_statement = """INSERT INTO health_2018 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2018.items():
        count += 1
        if count < len(values_dict_2018):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2019 Health Data
    insert_statement = """INSERT INTO health_2019 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2019.items():
        count += 1
        if count < len(values_dict_2019):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    

    connection.commit()
    print(cc, " health Data input Complete")
    print("--- %s seconds ---" % (time.time() - start_time))   


    
    
print("health Tables Complete")    
print("--- %s seconds ---" % (time.time() - start_time))    
    
# except (Exception, psycopg2.Error) as error :
#     print ("Error while fetching data from database", error)

# finally:
#     #closing database connection.
#     if(connection):
#         cursor.close()
#         connection.close()
#         print("Database connection is closed")

Fetching country codes
CC list created
Fetching Health Indicator Codes
Indicator code list created
AFG  health Data input Complete
--- 16.610764265060425 seconds ---
ALB  health Data input Complete
--- 34.47388172149658 seconds ---
DZA  health Data input Complete
--- 49.880167722702026 seconds ---
ASM  health Data input Complete
--- 66.45659279823303 seconds ---
AND  health Data input Complete
--- 81.79553985595703 seconds ---
AGO  health Data input Complete
--- 97.78918504714966 seconds ---
ATG  health Data input Complete
--- 114.96491169929504 seconds ---
ARG  health Data input Complete
--- 129.36404180526733 seconds ---
ARM  health Data input Complete
--- 145.35639119148254 seconds ---
ABW  health Data input Complete
--- 159.67916870117188 seconds ---
AUS  health Data input Complete
--- 175.07161235809326 seconds ---
AUT  health Data input Complete
--- 191.48645567893982 seconds ---
AZE  health Data input Complete
--- 208.7213294506073 seconds ---
BHS  health Data input Complete
--- 225.21709036827087 seconds ---
BHR  health Data input Complete
--- 240.24991416931152 seconds ---
BGD  health Data input Complete
--- 255.546240568161 seconds ---
BRB  health Data input Complete
--- 272.3828589916229 seconds ---
BLR  health Data input Complete
--- 286.2024886608124 seconds ---
BEL  health Data input Complete
--- 302.4185357093811 seconds ---
BLZ  health Data input Complete
--- 317.945458650589 seconds ---
BEN  health Data input Complete
--- 333.75174713134766 seconds ---
BMU  health Data input Complete
--- 347.86097598075867 seconds ---
BTN  health Data input Complete
--- 363.865681886673 seconds ---
BOL  health Data input Complete
--- 380.8686857223511 seconds ---
BIH  health Data input Complete
--- 399.75097274780273 seconds ---
BWA  health Data input Complete
--- 416.21560072898865 seconds ---
BRA  health Data input Complete
--- 432.62577056884766 seconds ---
VGB  health Data input Complete
--- 447.21652936935425 seconds ---
BRN  health Data input Complete
--- 463.4575002193451 seconds ---
BGR  health Data input Complete
--- 477.90917348861694 seconds ---
BFA  health Data input Complete
--- 494.51898074150085 seconds ---
BDI  health Data input Complete
--- 509.07669281959534 seconds ---
CPV  health Data input Complete
--- 524.7732560634613 seconds ---
KHM  health Data input Complete
--- 541.8954422473907 seconds ---
CMR  health Data input Complete
--- 557.4499037265778 seconds ---
CAN  health Data input Complete
--- 578.6174912452698 seconds ---
CYM  health Data input Complete
--- 598.9525825977325 seconds ---
CAF  health Data input Complete
--- 615.6983625888824 seconds ---
TCD  health Data input Complete
--- 630.6320631504059 seconds ---
CHI  health Data input Complete
--- 649.0854289531708 seconds ---
CHL  health Data input Complete
--- 667.4711644649506 seconds ---
CHN  health Data input Complete
--- 684.3342988491058 seconds ---
COL  health Data input Complete
--- 702.0458118915558 seconds ---
COM  health Data input Complete
--- 719.4299738407135 seconds ---
COD  health Data input Complete
--- 734.7191019058228 seconds ---
COG  health Data input Complete
--- 752.0039219856262 seconds ---
CRI  health Data input Complete
--- 771.3875877857208 seconds ---
CIV  health Data input Complete
--- 788.5306203365326 seconds ---
HRV  health Data input Complete
--- 805.7264337539673 seconds ---
CUB  health Data input Complete
--- 822.9557609558105 seconds ---
CUW  health Data input Complete
--- 840.1028175354004 seconds ---
CYP  health Data input Complete
--- 858.22176861763 seconds ---
CZE  health Data input Complete
--- 875.4477591514587 seconds ---
DNK  health Data input Complete
--- 893.3969011306763 seconds ---
DJI  health Data input Complete
--- 911.2665665149689 seconds ---
DMA  health Data input Complete
--- 928.4329752922058 seconds ---
DOM  health Data input Complete
--- 946.1922271251678 seconds ---
ECU  health Data input Complete
--- 964.1295187473297 seconds ---
EGY  health Data input Complete
--- 980.3525447845459 seconds ---
SLV  health Data input Complete
--- 995.9903349876404 seconds ---
GNQ  health Data input Complete
--- 1015.6942617893219 seconds ---
ERI  health Data input Complete
--- 1036.8329231739044 seconds ---
EST  health Data input Complete
--- 1058.362494468689 seconds ---
SWZ  health Data input Complete
--- 1079.528077840805 seconds ---
ETH  health Data input Complete
--- 1098.1843531131744 seconds ---
FRO  health Data input Complete
--- 1115.2321546077728 seconds ---
FJI  health Data input Complete
--- 1134.388931274414 seconds ---
FIN  health Data input Complete
--- 1156.0316989421844 seconds ---
FRA  health Data input Complete
--- 1175.2182745933533 seconds ---
PYF  health Data input Complete
--- 1195.8915431499481 seconds ---
GAB  health Data input Complete
--- 1213.6025993824005 seconds ---
GMB  health Data input Complete
--- 1230.470876455307 seconds ---
GEO  health Data input Complete
--- 1248.3265504837036 seconds ---
DEU  health Data input Complete
--- 1264.0351929664612 seconds ---
GHA  health Data input Complete
--- 1282.3467826843262 seconds ---
GIB  health Data input Complete
--- 1298.0485093593597 seconds ---
GRC  health Data input Complete
--- 1315.2378413677216 seconds ---
GRL  health Data input Complete
--- 1332.3783214092255 seconds ---
GRD  health Data input Complete
--- 1348.2011568546295 seconds ---
GUM  health Data input Complete
--- 1366.1612765789032 seconds ---
GTM  health Data input Complete
--- 1383.0610439777374 seconds ---
GIN  health Data input Complete
--- 1401.1983766555786 seconds ---
GNB  health Data input Complete
--- 1418.2931368350983 seconds ---
GUY  health Data input Complete
--- 1433.345615386963 seconds ---
HTI  health Data input Complete
--- 1449.6077122688293 seconds ---
HND  health Data input Complete
--- 1466.4087052345276 seconds ---
HKG  health Data input Complete
--- 1484.024064540863 seconds ---
HUN  health Data input Complete
--- 1500.4684090614319 seconds ---
ISL  health Data input Complete
--- 1517.5854125022888 seconds ---
IND  health Data input Complete
--- 1535.9291944503784 seconds ---
IDN  health Data input Complete
--- 1552.3586037158966 seconds ---
IRN  health Data input Complete
--- 1570.3497304916382 seconds ---
IRQ  health Data input Complete
--- 1588.8791790008545 seconds ---
IRL  health Data input Complete
--- 1607.4573163986206 seconds ---
IMN  health Data input Complete
--- 1625.181634902954 seconds ---
ISR  health Data input Complete
--- 1643.0309665203094 seconds ---
ITA  health Data input Complete
--- 1661.467304468155 seconds ---
JAM  health Data input Complete
--- 1680.5092601776123 seconds ---
JPN  health Data input Complete
--- 1698.3219537734985 seconds ---
JOR  health Data input Complete
--- 1713.5468842983246 seconds ---
KAZ  health Data input Complete
--- 1731.0889134407043 seconds ---
KEN  health Data input Complete
--- 1750.2300136089325 seconds ---
KIR  health Data input Complete
--- 1768.871064901352 seconds ---
PRK  health Data input Complete
--- 1787.7057449817657 seconds ---
400
KOR  health Data input Complete
--- 1805.2655441761017 seconds ---
XKX  health Data input Complete
--- 1821.58021402359 seconds ---
KWT  health Data input Complete
--- 1839.2347140312195 seconds ---
KGZ  health Data input Complete
--- 1858.9395909309387 seconds ---
LAO  health Data input Complete
--- 1875.6177940368652 seconds ---
LVA  health Data input Complete
--- 1892.0724635124207 seconds ---
LBN  health Data input Complete
--- 1908.6320097446442 seconds ---
LSO  health Data input Complete
--- 1929.4875793457031 seconds ---
LBR  health Data input Complete
--- 1949.1149048805237 seconds ---
LBY  health Data input Complete
--- 1968.171779870987 seconds ---
LIE  health Data input Complete
--- 1986.1145808696747 seconds ---
LTU  health Data input Complete
--- 2006.5292220115662 seconds ---
LUX  health Data input Complete
--- 2026.979489326477 seconds ---
MAC  health Data input Complete
--- 2046.1991138458252 seconds ---
MDG  health Data input Complete
--- 2062.973193883896 seconds ---
MWI  health Data input Complete
--- 2084.5031504631042 seconds ---
MYS  health Data input Complete
--- 2102.2229211330414 seconds ---
MDV  health Data input Complete
--- 2121.144340276718 seconds ---

MLI  health Data input Complete
--- 2138.8095257282257 seconds ---
MLT  health Data input Complete
--- 2157.8842837810516 seconds ---
MHL  health Data input Complete
--- 2174.798605442047 seconds ---
MRT  health Data input Complete
--- 2194.506465435028 seconds ---
MUS  health Data input Complete
--- 2213.0008697509766 seconds ---
MEX  health Data input Complete
--- 2233.911271095276 seconds ---
FSM  health Data input Complete
--- 2258.3928735256195 seconds ---
MDA  health Data input Complete
--- 2279.452292203903 seconds ---
MCO  health Data input Complete
--- 2300.6544148921967 seconds ---
MNG  health Data input Complete
--- 2321.9461262226105 seconds ---
MNE  health Data input Complete
--- 2342.216468334198 seconds ---
MAR  health Data input Complete
--- 2362.3291158676147 seconds ---
MOZ  health Data input Complete
--- 2382.0954122543335 seconds ---
MMR  health Data input Complete
--- 2400.8988173007965 seconds ---
NAM  health Data input Complete
--- 2420.228991508484 seconds ---
NPL  health Data input Complete
--- 2439.0443267822266 seconds ---
NLD  health Data input Complete
--- 2461.723708629608 seconds ---
NCL  health Data input Complete
--- 2481.441109895706 seconds ---
NZL  health Data input Complete
--- 2502.792120218277 seconds ---
NIC  health Data input Complete
--- 2525.2419781684875 seconds ---
NER  health Data input Complete
--- 2549.763908624649 seconds ---
NGA  health Data input Complete
--- 2573.2069714069366 seconds ---
400
400
MKD  health Data input Complete
--- 2592.412050962448 seconds ---
MNP  health Data input Complete
--- 2611.373300552368 seconds ---
NOR  health Data input Complete
--- 2637.0443394184113 seconds ---
OMN  health Data input Complete
--- 2659.9046738147736 seconds ---
PAK  health Data input Complete
--- 2679.531706571579 seconds ---
PLW  health Data input Complete
--- 2699.115841150284 seconds ---
PAN  health Data input Complete
--- 2718.531949520111 seconds ---
PNG  health Data input Complete
--- 2735.338869333267 seconds ---
PRY  health Data input Complete
--- 2754.9853858947754 seconds ---
PER  health Data input Complete
--- 2776.1815333366394 seconds ---
PHL  health Data input Complete
--- 2795.1380393505096 seconds ---
POL  health Data input Complete
--- 2811.1026458740234 seconds ---
PRT  health Data input Complete
--- 2826.367415189743 seconds ---
PRI  health Data input Complete
--- 2842.258937597275 seconds ---
QAT  health Data input Complete
--- 2860.5345237255096 seconds ---
ROU  health Data input Complete
--- 2880.3047094345093 seconds ---
RUS  health Data input Complete
--- 2899.0443353652954 seconds ---
RWA  health Data input Complete
--- 2916.453868150711 seconds ---
WSM  health Data input Complete
--- 2935.783859014511 seconds ---
SMR  health Data input Complete
--- 2956.257150411606 seconds ---
STP  health Data input Complete
--- 2973.4096422195435 seconds ---
SAU  health Data input Complete
--- 2991.166877269745 seconds ---
SEN  health Data input Complete
--- 3006.5734498500824 seconds ---
SRB  health Data input Complete
--- 3024.592931509018 seconds ---
SYC  health Data input Complete
--- 3042.949326992035 seconds ---
SLE  health Data input Complete
--- 3060.434280872345 seconds ---
SGP  health Data input Complete
--- 3077.8967452049255 seconds ---
SXM  health Data input Complete
--- 3095.581744670868 seconds ---
SVK  health Data input Complete
--- 3112.5458431243896 seconds ---
SVN  health Data input Complete
--- 3128.7784440517426 seconds ---
SLB  health Data input Complete
--- 3146.6326513290405 seconds ---
SOM  health Data input Complete
--- 3166.123147726059 seconds ---
ZAF  health Data input Complete
--- 3183.0815057754517 seconds ---
SSD  health Data input Complete
--- 3200.723271369934 seconds ---
ESP  health Data input Complete
--- 3221.4647846221924 seconds ---
LKA  health Data input Complete
--- 3238.7312200069427 seconds ---
KNA  health Data input Complete
--- 3257.3690073490143 seconds ---
LCA  health Data input Complete
--- 3273.1052520275116 seconds ---
MAF  health Data input Complete
--- 3290.830392599106 seconds ---
VCT  health Data input Complete
--- 3307.8514215946198 seconds ---
SDN  health Data input Complete
--- 3326.6773948669434 seconds ---
SUR  health Data input Complete
--- 3344.0882024765015 seconds ---
SWE  health Data input Complete
--- 3363.9882895946503 seconds ---
CHE  health Data input Complete
--- 3380.5436844825745 seconds ---
SYR  health Data input Complete
--- 3398.031759262085 seconds ---
TJK  health Data input Complete
--- 3415.2753405570984 seconds ---
TZA  health Data input Complete
--- 3432.303364753723 seconds ---
400
THA  health Data input Complete
--- 3450.386222600937 seconds ---
TLS  health Data input Complete
--- 3467.9396693706512 seconds ---
TGO  health Data input Complete
--- 3488.880807876587 seconds ---
TON  health Data input Complete
--- 3505.9308354854584 seconds ---
TTO  health Data input Complete
--- 3523.081833600998 seconds ---
TUN  health Data input Complete
--- 3539.805160045624 seconds ---
TUR  health Data input Complete
--- 3558.7510979175568 seconds ---
TKM  health Data input Complete
--- 3575.3240151405334 seconds ---
TCA  health Data input Complete
--- 3592.8668525218964 seconds ---
TUV  health Data input Complete
--- 3610.3409748077393 seconds ---
UGA  health Data input Complete
--- 3628.0279970169067 seconds ---
UKR  health Data input Complete
--- 3645.020120859146 seconds ---
ARE  health Data input Complete
--- 3663.9471428394318 seconds ---
GBR  health Data input Complete
--- 3681.91188788414 seconds ---
USA  health Data input Complete
--- 3700.2148003578186 seconds ---
URY  health Data input Complete
--- 3718.072355747223 seconds ---
UZB  health Data input Complete
--- 3743.854779481888 seconds ---
VUT  health Data input Complete
--- 3764.348522424698 seconds ---
VEN  health Data input Complete
--- 3782.9434909820557 seconds ---
VNM  health Data input Complete
--- 3800.952877998352 seconds ---
VIR  health Data input Complete
--- 3817.7651653289795 seconds ---
PSE  health Data input Complete
--- 3836.978053331375 seconds ---
YEM  health Data input Complete
--- 3853.2960743904114 seconds ---
ZMB  health Data input Complete
--- 3871.1337406635284 seconds ---
ZWE  health Data input Complete
--- 3887.4682161808014 seconds ---
health Tables Complete
--- 3887.4682161808014 seconds ---

In [23]:
### Fill Education Factors Tables 2010-2019 in Database
import requests
import json
import pandas as pd
import time

# try:
connection = psycopg2.connect(
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

cursor = connection.cursor()

countries_query = "select country_code from countries"
cursor.execute(countries_query)
print ("Fetching country codes")
countries = cursor.fetchall()

cc_list = []

for cc in countries:
    cc_list.append(cc[0])
print ("CC list created")

education_indicator_query = "select indicator_code from education_factors"
cursor.execute(education_indicator_query)
print ("Fetching Education Indicator Codes")
education_indicators = cursor.fetchall()

education_indicator_list = []
for indicator in education_indicators:
    education_indicator_list.append(indicator[0].strip())
print ("Indicator code list created")

start_time = time.time()
for cc in cc_list:
    
    ### If api calls time out, I don't want to repeat table entries, so checking if they exist and moving on if they do
    check_statement = 'select * from education_2019 where "COUNTRY.CODE" =  ' + "'" + cc + "'"
    cursor.execute(check_statement)
    if bool(cursor.rowcount):
        continue
        
    values_dict_2010 = {'COUNTRY.CODE': cc}   ### dictionaries to hold values pulled from API
    values_dict_2011 = {'COUNTRY.CODE': cc}
    values_dict_2012 = {'COUNTRY.CODE': cc}   
    values_dict_2013 = {'COUNTRY.CODE': cc}   
    values_dict_2014 = {'COUNTRY.CODE': cc}   
    values_dict_2015 = {'COUNTRY.CODE': cc}   
    values_dict_2016 = {'COUNTRY.CODE': cc}   
    values_dict_2017 = {'COUNTRY.CODE': cc}   
    values_dict_2018 = {'COUNTRY.CODE': cc}   
    values_dict_2019 = {'COUNTRY.CODE': cc}     

    for indicator in education_indicators:
        time.sleep(1)  ### Delay for API calls
        indicator_in = indicator[0].strip()
        url = ("http://api.worldbank.org/v2/country/%s/indicator/%s?format=json" % (cc, indicator_in))
        r = requests.get(url = url)
        if r.status_code == 200:
            data_pull = r.json()
            data_pull = json.dumps(data_pull)
            data_pull = json.loads(data_pull)
            
            ### years 2010 - 2019 correspond to indices 10 - 1, respectively
            values_dict_2010[indicator_in] = data_pull[1][10]['value']
            values_dict_2011[indicator_in] = data_pull[1][9]['value']
            values_dict_2012[indicator_in] = data_pull[1][8]['value']
            values_dict_2013[indicator_in] = data_pull[1][7]['value']
            values_dict_2014[indicator_in] = data_pull[1][6]['value']
            values_dict_2015[indicator_in] = data_pull[1][5]['value']
            values_dict_2016[indicator_in] = data_pull[1][4]['value']
            values_dict_2017[indicator_in] = data_pull[1][3]['value']
            values_dict_2018[indicator_in] = data_pull[1][2]['value']
            values_dict_2019[indicator_in] = data_pull[1][1]['value']

        else:
            print(r.status_code)
            continue
        
    
    ### 2010 Education Data
    insert_statement = """INSERT INTO education_2010 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2010.items():
        count += 1
        if count < len(values_dict_2010):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2011 Education Data    
    insert_statement = """INSERT INTO education_2011 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2011.items():
        count += 1
        if count < len(values_dict_2011):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2012 Education Data
    insert_statement = """INSERT INTO education_2012 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2012.items():
        count += 1
        if count < len(values_dict_2012):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2013 Education Data
    insert_statement = """INSERT INTO education_2013 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2013.items():
        count += 1
        if count < len(values_dict_2013):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2014 Education Data    
    insert_statement = """INSERT INTO education_2014 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2014.items():
        count += 1
        if count < len(values_dict_2014):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2015 Education Data
    insert_statement = """INSERT INTO education_2015 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2015.items():
        count += 1
        if count < len(values_dict_2015):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2016 Education Data
    insert_statement = """INSERT INTO education_2016 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2016.items():
        count += 1
        if count < len(values_dict_2016):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2017 Education Data
    insert_statement = """INSERT INTO education_2017 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2017.items():
        count += 1
        if count < len(values_dict_2017):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2018 Education Data    
    insert_statement = """INSERT INTO education_2018 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2018.items():
        count += 1
        if count < len(values_dict_2018):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2019 Education Data
    insert_statement = """INSERT INTO education_2019 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2019.items():
        count += 1
        if count < len(values_dict_2019):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    

    connection.commit()
    print(cc, " Education Data input Complete")
    print("--- %s seconds ---" % (time.time() - start_time))   


    
    
print("Education Tables Complete")    
print("--- %s seconds ---" % (time.time() - start_time))    
    
# except (Exception, psycopg2.Error) as error :
#     print ("Error while fetching data from database", error)

# finally:
#     #closing database connection.
#     if(connection):
#         cursor.close()
#         connection.close()
#         print("Database connection is closed")

Fetching country codes
CC list created
Fetching Education Indicator Codes
Indicator code list created
BGD  Education Data input Complete
--- 23.612242221832275 seconds ---
BRB  Education Data input Complete
--- 52.94184851646423 seconds ---
BLR  Education Data input Complete
--- 81.8146333694458 seconds ---
BEL  Education Data input Complete
--- 113.69424319267273 seconds ---
400
BLZ  Education Data input Complete
--- 139.46958780288696 seconds ---
BEN  Education Data input Complete
--- 163.75663042068481 seconds ---
BMU  Education Data input Complete
--- 187.35155701637268 seconds ---
BTN  Education Data input Complete
--- 214.30811858177185 seconds ---
BOL  Education Data input Complete
--- 238.24076890945435 seconds ---
BIH  Education Data input Complete
--- 264.84922528266907 seconds ---
BWA  Education Data input Complete
--- 292.6109848022461 seconds ---
BRA  Education Data input Complete
--- 322.97254633903503 seconds ---
VGB  Education Data input Complete
--- 349.12343883514404 seconds ---
BRN  Education Data input Complete
--- 379.27657866477966 seconds ---
BGR  Education Data input Complete
--- 402.82234382629395 seconds ---
BFA  Education Data input Complete
--- 429.492214679718 seconds ---
400
BDI  Education Data input Complete
--- 461.6841838359833 seconds ---
CPV  Education Data input Complete
--- 494.3560917377472 seconds ---
KHM  Education Data input Complete
--- 524.4666519165039 seconds ---
CMR  Education Data input Complete
--- 557.0594944953918 seconds ---
400
400
400
400
CAN  Education Data input Complete
--- 584.9070858955383 seconds ---
CYM  Education Data input Complete
--- 614.6802563667297 seconds ---
CAF  Education Data input Complete
--- 639.4949052333832 seconds ---
TCD  Education Data input Complete
--- 668.6622939109802 seconds ---
CHI  Education Data input Complete
--- 701.7843818664551 seconds ---
CHL  Education Data input Complete
--- 732.7669589519501 seconds ---
CHN  Education Data input Complete
--- 760.9607181549072 seconds ---
COL  Education Data input Complete
--- 787.1360092163086 seconds ---
COM  Education Data input Complete
--- 815.6903495788574 seconds ---
COD  Education Data input Complete
--- 850.9569802284241 seconds ---
COG  Education Data input Complete
--- 882.677517414093 seconds ---
CRI  Education Data input Complete
--- 913.9045240879059 seconds ---
CIV  Education Data input Complete
--- 942.5880436897278 seconds ---
HRV  Education Data input Complete
--- 974.7289388179779 seconds ---
CUB  Education Data input Complete
--- 1009.2112641334534 seconds ---
CUW  Education Data input Complete
--- 1035.5278868675232 seconds ---
CYP  Education Data input Complete
--- 1064.5468423366547 seconds ---
CZE  Education Data input Complete
--- 1091.4672372341156 seconds ---
DNK  Education Data input Complete
--- 1116.98668384552 seconds ---
DJI  Education Data input Complete
--- 1143.2633402347565 seconds ---
DMA  Education Data input Complete
--- 1177.6708235740662 seconds ---
DOM  Education Data input Complete
--- 1206.8481669425964 seconds ---
ECU  Education Data input Complete
--- 1236.6024312973022 seconds ---
EGY  Education Data input Complete
--- 1267.3664681911469 seconds ---
SLV  Education Data input Complete
--- 1297.9882624149323 seconds ---
GNQ  Education Data input Complete
--- 1328.126721382141 seconds ---
ERI  Education Data input Complete
--- 1359.365157842636 seconds ---
EST  Education Data input Complete
--- 1388.72017288208 seconds ---
SWZ  Education Data input Complete
--- 1422.734709262848 seconds ---
ETH  Education Data input Complete
--- 1453.7418508529663 seconds ---
FRO  Education Data input Complete
--- 1478.8842730522156 seconds ---
FJI  Education Data input Complete
--- 1510.2791135311127 seconds ---
FIN  Education Data input Complete
--- 1538.8265464305878 seconds ---
FRA  Education Data input Complete
--- 1571.7765316963196 seconds ---
PYF  Education Data input Complete
--- 1597.9752056598663 seconds ---
GAB  Education Data input Complete
--- 1627.870837211609 seconds ---
GMB  Education Data input Complete
--- 1657.3701059818268 seconds ---
GEO  Education Data input Complete
--- 1681.9641542434692 seconds ---
DEU  Education Data input Complete
--- 1706.5638654232025 seconds ---
GHA  Education Data input Complete
--- 1731.5952479839325 seconds ---
GIB  Education Data input Complete
--- 1759.7399561405182 seconds ---
GRC  Education Data input Complete
--- 1789.5269951820374 seconds ---
GRL  Education Data input Complete
--- 1817.6286237239838 seconds ---
GRD  Education Data input Complete
--- 1845.2509543895721 seconds ---
GUM  Education Data input Complete
--- 1872.4091730117798 seconds ---
GTM  Education Data input Complete
--- 1903.9789962768555 seconds ---
GIN  Education Data input Complete
--- 1931.0265407562256 seconds ---
GNB  Education Data input Complete
--- 1961.9339044094086 seconds ---
GUY  Education Data input Complete
--- 1991.2208054065704 seconds ---
HTI  Education Data input Complete
--- 2020.1256384849548 seconds ---
HND  Education Data input Complete
--- 2050.563536167145 seconds ---
HKG  Education Data input Complete
--- 2076.804044485092 seconds ---
HUN  Education Data input Complete
--- 2111.086028575897 seconds ---
400
ISL  Education Data input Complete
--- 2137.869875192642 seconds ---
IND  Education Data input Complete
--- 2166.0282678604126 seconds ---
IDN  Education Data input Complete
--- 2194.0139060020447 seconds ---
IRN  Education Data input Complete
--- 2228.666264772415 seconds ---
IRQ  Education Data input Complete
--- 2252.161838054657 seconds ---
IRL  Education Data input Complete
--- 2278.9904220104218 seconds ---
IMN  Education Data input Complete
--- 2305.1328053474426 seconds ---
ISR  Education Data input Complete
--- 2331.923675775528 seconds ---
ITA  Education Data input Complete
--- 2359.9637999534607 seconds ---
JAM  Education Data input Complete
--- 2387.897778749466 seconds ---
400
JPN  Education Data input Complete
--- 2413.0298340320587 seconds ---
JOR  Education Data input Complete
--- 2440.817976951599 seconds ---
400
KAZ  Education Data input Complete
--- 2468.8677706718445 seconds ---
400
KEN  Education Data input Complete
--- 2497.4342153072357 seconds ---
KIR  Education Data input Complete
--- 2523.810025691986 seconds ---
PRK  Education Data input Complete
--- 2551.235352754593 seconds ---
KOR  Education Data input Complete
--- 2582.760749578476 seconds ---
XKX  Education Data input Complete
--- 2607.0716078281403 seconds ---
KWT  Education Data input Complete
--- 2632.864903688431 seconds ---
KGZ  Education Data input Complete
--- 2658.28750538826 seconds ---
LAO  Education Data input Complete
--- 2683.9680774211884 seconds ---
LVA  Education Data input Complete
--- 2710.8029766082764 seconds ---
LBN  Education Data input Complete
--- 2737.2187802791595 seconds ---
LSO  Education Data input Complete
--- 2761.793914079666 seconds ---
LBR  Education Data input Complete
--- 2787.5393056869507 seconds ---
LBY  Education Data input Complete
--- 2815.223738193512 seconds ---
LIE  Education Data input Complete
--- 2840.361486196518 seconds ---
LTU  Education Data input Complete
--- 2867.0316393375397 seconds ---
LUX  Education Data input Complete
--- 2894.6257150173187 seconds ---
MAC  Education Data input Complete
--- 2921.130637407303 seconds ---
MDG  Education Data input Complete
--- 2947.2874298095703 seconds ---
MWI  Education Data input Complete
--- 2975.2274158000946 seconds ---
MYS  Education Data input Complete
--- 3003.7908957004547 seconds ---
MDV  Education Data input Complete
--- 3028.306457042694 seconds ---
MLI  Education Data input Complete
--- 3051.970491170883 seconds ---
MLT  Education Data input Complete
--- 3075.221124649048 seconds ---
MHL  Education Data input Complete
--- 3102.5090696811676 seconds ---
MRT  Education Data input Complete
--- 3128.6544349193573 seconds ---
MUS  Education Data input Complete
--- 3151.97248339653 seconds ---
MEX  Education Data input Complete
--- 3177.602241754532 seconds ---
FSM  Education Data input Complete
--- 3205.3922233581543 seconds ---
MDA  Education Data input Complete
--- 3230.4103429317474 seconds ---
MCO  Education Data input Complete
--- 3257.399927377701 seconds ---

MNG  Education Data input Complete
--- 3281.3350677490234 seconds ---
MNE  Education Data input Complete
--- 3307.9478974342346 seconds ---
MAR  Education Data input Complete
--- 3334.358165740967 seconds ---
MOZ  Education Data input Complete
--- 3359.0018446445465 seconds ---
MMR  Education Data input Complete
--- 3382.230130672455 seconds ---
NAM  Education Data input Complete
--- 3403.892719268799 seconds ---
NPL  Education Data input Complete
--- 3428.3360476493835 seconds ---
NLD  Education Data input Complete
--- 3453.6312379837036 seconds ---
NCL  Education Data input Complete
--- 3480.8583137989044 seconds ---
NZL  Education Data input Complete
--- 3506.148304462433 seconds ---
NIC  Education Data input Complete
--- 3535.697018146515 seconds ---
NER  Education Data input Complete
--- 3560.5422365665436 seconds ---
NGA  Education Data input Complete
--- 3586.8281292915344 seconds ---
MKD  Education Data input Complete
--- 3611.029231786728 seconds ---
MNP  Education Data input Complete
--- 3636.698799133301 seconds ---
NOR  Education Data input Complete
--- 3661.0650038719177 seconds ---
OMN  Education Data input Complete
--- 3684.5354194641113 seconds ---
PAK  Education Data input Complete
--- 3709.67848443985 seconds ---
PLW  Education Data input Complete
--- 3733.0905261039734 seconds ---
PAN  Education Data input Complete
--- 3756.775260448456 seconds ---
PNG  Education Data input Complete
--- 3779.9070885181427 seconds ---
PRY  Education Data input Complete
--- 3807.453353881836 seconds ---
PER  Education Data input Complete
--- 3830.02010846138 seconds ---
PHL  Education Data input Complete
--- 3853.549460887909 seconds ---
POL  Education Data input Complete
--- 3876.4521248340607 seconds ---
PRT  Education Data input Complete
--- 3898.252333164215 seconds ---
PRI  Education Data input Complete
--- 3924.4952459335327 seconds ---
QAT  Education Data input Complete
--- 3947.316076040268 seconds ---
ROU  Education Data input Complete
--- 3972.146486520767 seconds ---
RUS  Education Data input Complete
--- 3997.403029680252 seconds ---
RWA  Education Data input Complete
--- 4023.211263656616 seconds ---
WSM  Education Data input Complete
--- 4048.776052236557 seconds ---
SMR  Education Data input Complete
--- 4073.2573897838593 seconds ---
STP  Education Data input Complete
--- 4096.622774839401 seconds ---
SAU  Education Data input Complete
--- 4119.507418632507 seconds ---
SEN  Education Data input Complete
--- 4142.092967271805 seconds ---
SRB  Education Data input Complete
--- 4164.970666408539 seconds ---
SYC  Education Data input Complete
--- 4187.306303977966 seconds ---
SLE  Education Data input Complete
--- 4209.858746767044 seconds ---
SGP  Education Data input Complete
--- 4233.005127429962 seconds ---
SXM  Education Data input Complete
--- 4256.787637710571 seconds ---
SVK  Education Data input Complete
--- 4279.754174947739 seconds ---
SVN  Education Data input Complete
--- 4304.098633766174 seconds ---
SLB  Education Data input Complete
--- 4328.650034427643 seconds ---
SOM  Education Data input Complete
--- 4351.855184078217 seconds ---
400
ZAF  Education Data input Complete
--- 4375.217874765396 seconds ---
SSD  Education Data input Complete
--- 4399.179524183273 seconds ---
ESP  Education Data input Complete
--- 4421.511978149414 seconds ---
LKA  Education Data input Complete
--- 4445.500604629517 seconds ---
KNA  Education Data input Complete
--- 4471.774690628052 seconds ---
LCA  Education Data input Complete
--- 4499.040567874908 seconds ---
MAF  Education Data input Complete
--- 4522.379169225693 seconds ---
VCT  Education Data input Complete
--- 4545.820133686066 seconds ---
SDN  Education Data input Complete
--- 4571.6537663936615 seconds ---
SUR  Education Data input Complete
--- 4597.116582870483 seconds ---
SWE  Education Data input Complete
--- 4620.4383456707 seconds ---
CHE  Education Data input Complete
--- 4644.253374099731 seconds ---
SYR  Education Data input Complete
--- 4668.413915395737 seconds ---
TJK  Education Data input Complete
--- 4691.061472415924 seconds ---
TZA  Education Data input Complete
--- 4715.048193454742 seconds ---
THA  Education Data input Complete
--- 4739.160687685013 seconds ---
TLS  Education Data input Complete
--- 4761.77420258522 seconds ---
TGO  Education Data input Complete
--- 4786.334364891052 seconds ---
TON  Education Data input Complete
--- 4811.01384806633 seconds ---
TTO  Education Data input Complete
--- 4834.869345903397 seconds ---
TUN  Education Data input Complete
--- 4857.8004586696625 seconds ---
TUR  Education Data input Complete
--- 4881.42965555191 seconds ---
TKM  Education Data input Complete
--- 4904.516586303711 seconds ---
TCA  Education Data input Complete
--- 4928.576730489731 seconds ---
TUV  Education Data input Complete
--- 4952.773475646973 seconds ---
UGA  Education Data input Complete
--- 4977.42204451561 seconds ---
UKR  Education Data input Complete
--- 5001.364957332611 seconds ---
ARE  Education Data input Complete
--- 5023.576591491699 seconds ---
GBR  Education Data input Complete
--- 5047.293689250946 seconds ---
USA  Education Data input Complete
--- 5071.236729621887 seconds ---
URY  Education Data input Complete
--- 5093.581394433975 seconds ---
UZB  Education Data input Complete
--- 5118.511007070541 seconds ---
VUT  Education Data input Complete
--- 5142.257433652878 seconds ---
VEN  Education Data input Complete
--- 5164.262334823608 seconds ---
VNM  Education Data input Complete
--- 5187.141077041626 seconds ---
VIR  Education Data input Complete
--- 5210.995843410492 seconds ---
PSE  Education Data input Complete
--- 5234.703534126282 seconds ---
YEM  Education Data input Complete
--- 5258.928704023361 seconds ---
ZMB  Education Data input Complete
--- 5282.723103761673 seconds ---
ZWE  Education Data input Complete
--- 5305.729043722153 seconds ---
Education Tables Complete
--- 5305.729043722153 seconds ---

In [24]:
### Fill Infrastructure Factors Tables 2010-2019 in Database
import requests
import json
import pandas as pd
import time

# try:
connection = psycopg2.connect(
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

cursor = connection.cursor()

countries_query = "select country_code from countries"
cursor.execute(countries_query)
print ("Fetching country codes")
countries = cursor.fetchall()

cc_list = []

for cc in countries:
    cc_list.append(cc[0])
print ("CC list created")

infra_indicator_query = "select indicator_code from infra_factors"
cursor.execute(infra_indicator_query)
print ("Fetching Infrastructure Indicator Codes")
infra_indicators = cursor.fetchall()

infra_indicator_list = []
for indicator in infra_indicators:
    infra_indicator_list.append(indicator[0].strip())
print ("Indicator code list created")

start_time = time.time()
for cc in cc_list:
    
    ### If api calls time out, I don't want to repeat table entries, so checking if they exist and moving on if they do
    check_statement = 'select * from infra_2019 where "COUNTRY.CODE" =  ' + "'" + cc + "'"
    cursor.execute(check_statement)
    if bool(cursor.rowcount):
        continue
        
    values_dict_2010 = {'COUNTRY.CODE': cc}   ### dictionaries to hold values pulled from API
    values_dict_2011 = {'COUNTRY.CODE': cc}
    values_dict_2012 = {'COUNTRY.CODE': cc}   
    values_dict_2013 = {'COUNTRY.CODE': cc}   
    values_dict_2014 = {'COUNTRY.CODE': cc}   
    values_dict_2015 = {'COUNTRY.CODE': cc}   
    values_dict_2016 = {'COUNTRY.CODE': cc}   
    values_dict_2017 = {'COUNTRY.CODE': cc}   
    values_dict_2018 = {'COUNTRY.CODE': cc}   
    values_dict_2019 = {'COUNTRY.CODE': cc}     

    for indicator in infra_indicators:
        time.sleep(1)  ### Delay for API calls
        indicator_in = indicator[0].strip()
        url = ("http://api.worldbank.org/v2/country/%s/indicator/%s?format=json" % (cc, indicator_in))
        r = requests.get(url = url)
        if r.status_code == 200:
            data_pull = r.json()
            data_pull = json.dumps(data_pull)
            data_pull = json.loads(data_pull)
            
            ### years 2010 - 2019 correspond to indices 10 - 1, respectively
            values_dict_2010[indicator_in] = data_pull[1][10]['value']
            values_dict_2011[indicator_in] = data_pull[1][9]['value']
            values_dict_2012[indicator_in] = data_pull[1][8]['value']
            values_dict_2013[indicator_in] = data_pull[1][7]['value']
            values_dict_2014[indicator_in] = data_pull[1][6]['value']
            values_dict_2015[indicator_in] = data_pull[1][5]['value']
            values_dict_2016[indicator_in] = data_pull[1][4]['value']
            values_dict_2017[indicator_in] = data_pull[1][3]['value']
            values_dict_2018[indicator_in] = data_pull[1][2]['value']
            values_dict_2019[indicator_in] = data_pull[1][1]['value']

        else:
            print(r.status_code)
            continue
        
    
    ### 2010 Infrastructure Data
    insert_statement = """INSERT INTO infra_2010 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2010.items():
        count += 1
        if count < len(values_dict_2010):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2011 Infrastructure Data    
    insert_statement = """INSERT INTO infra_2011 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2011.items():
        count += 1
        if count < len(values_dict_2011):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2012 Infrastructure Data
    insert_statement = """INSERT INTO infra_2012 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2012.items():
        count += 1
        if count < len(values_dict_2012):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2013 Infrastructure Data
    insert_statement = """INSERT INTO infra_2013 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2013.items():
        count += 1
        if count < len(values_dict_2013):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2014 Infrastructure Data    
    insert_statement = """INSERT INTO infra_2014 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2014.items():
        count += 1
        if count < len(values_dict_2014):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2015 Infrastructure Data
    insert_statement = """INSERT INTO infra_2015 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2015.items():
        count += 1
        if count < len(values_dict_2015):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2016 Infrastructure Data
    insert_statement = """INSERT INTO infra_2016 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2016.items():
        count += 1
        if count < len(values_dict_2016):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2017 Infrastructure Data
    insert_statement = """INSERT INTO infra_2017 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2017.items():
        count += 1
        if count < len(values_dict_2017):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2018 Infrastructure Data    
    insert_statement = """INSERT INTO infra_2018 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2018.items():
        count += 1
        if count < len(values_dict_2018):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2019 Infrastructure Data
    insert_statement = """INSERT INTO infra_2019 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2019.items():
        count += 1
        if count < len(values_dict_2019):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    

    connection.commit()
    print(cc, " Infrastructure Data input Complete")
    print("--- %s seconds ---" % (time.time() - start_time))   

cursor.close()
connection.close()


print("Infrastructure Tables Complete")    
print("--- %s seconds ---" % (time.time() - start_time))    
    
# except (Exception, psycopg2.Error) as error :
#     print ("Error while fetching data from database", error)

# finally:
#     #closing database connection.
#     if(connection):
#         cursor.close()
#         connection.close()
#         print("Database connection is closed")

Fetching country codes
CC list created
Fetching Infrastructure Indicator Codes
Indicator code list created
AFG  Infrastructure Data input Complete
--- 32.37103986740112 seconds ---
ALB  Infrastructure Data input Complete
--- 65.52952313423157 seconds ---
DZA  Infrastructure Data input Complete
--- 97.36439800262451 seconds ---
400
ASM  Infrastructure Data input Complete
--- 128.37790966033936 seconds ---
AND  Infrastructure Data input Complete
--- 162.34504294395447 seconds ---
AGO  Infrastructure Data input Complete
--- 201.32783603668213 seconds ---
ATG  Infrastructure Data input Complete
--- 238.33123469352722 seconds ---
ARG  Infrastructure Data input Complete
--- 280.10109877586365 seconds ---
400
ARM  Infrastructure Data input Complete
--- 323.82563614845276 seconds ---
ABW  Infrastructure Data input Complete
--- 357.2559974193573 seconds ---
AUS  Infrastructure Data input Complete
--- 397.0958957672119 seconds ---
AUT  Infrastructure Data input Complete
--- 435.8182153701782 seconds ---
AZE  Infrastructure Data input Complete
--- 475.6628797054291 seconds ---
BHS  Infrastructure Data input Complete
--- 513.7585306167603 seconds ---
400
BHR  Infrastructure Data input Complete
--- 550.5623281002045 seconds ---
BGD  Infrastructure Data input Complete
--- 591.4930963516235 seconds ---
BRB  Infrastructure Data input Complete
--- 633.6942000389099 seconds ---
BLR  Infrastructure Data input Complete
--- 672.0691442489624 seconds ---
BEL  Infrastructure Data input Complete
--- 713.94495677948 seconds ---
BLZ  Infrastructure Data input Complete
--- 756.4336950778961 seconds ---
BEN  Infrastructure Data input Complete
--- 795.0043301582336 seconds ---
BMU  Infrastructure Data input Complete
--- 834.4286091327667 seconds ---
BTN  Infrastructure Data input Complete
--- 877.417638540268 seconds ---
BOL  Infrastructure Data input Complete
--- 919.1912562847137 seconds ---
BIH  Infrastructure Data input Complete
--- 955.7253844738007 seconds ---
BWA  Infrastructure Data input Complete
--- 993.7801268100739 seconds ---
BRA  Infrastructure Data input Complete
--- 1032.7266445159912 seconds ---
VGB  Infrastructure Data input Complete
--- 1070.7069907188416 seconds ---
BRN  Infrastructure Data input Complete
--- 1108.9745826721191 seconds ---
BGR  Infrastructure Data input Complete
--- 1148.6259434223175 seconds ---
BFA  Infrastructure Data input Complete
--- 1191.7012376785278 seconds ---
BDI  Infrastructure Data input Complete
--- 1236.5623269081116 seconds ---
CPV  Infrastructure Data input Complete
--- 1273.6567268371582 seconds ---
KHM  Infrastructure Data input Complete
--- 1316.7417075634003 seconds ---
CMR  Infrastructure Data input Complete
--- 1356.646686553955 seconds ---
CAN  Infrastructure Data input Complete
--- 1398.8616080284119 seconds ---
CYM  Infrastructure Data input Complete
--- 1439.201932668686 seconds ---
CAF  Infrastructure Data input Complete
--- 1487.8655517101288 seconds ---
TCD  Infrastructure Data input Complete
--- 1528.9880113601685 seconds ---
CHI  Infrastructure Data input Complete
--- 1574.449066400528 seconds ---
CHL  Infrastructure Data input Complete
--- 1614.3773367404938 seconds ---
CHN  Infrastructure Data input Complete
--- 1657.5509185791016 seconds ---
COL  Infrastructure Data input Complete
--- 1699.9553718566895 seconds ---
COM  Infrastructure Data input Complete
--- 1744.4865591526031 seconds ---
COD  Infrastructure Data input Complete
--- 1786.345632314682 seconds ---
COG  Infrastructure Data input Complete
--- 1822.7163071632385 seconds ---
CRI  Infrastructure Data input Complete
--- 1865.2942378520966 seconds ---
400
CIV  Infrastructure Data input Complete
--- 1904.030012845993 seconds ---
HRV  Infrastructure Data input Complete
--- 1941.3706994056702 seconds ---
CUB  Infrastructure Data input Complete
--- 1981.7653350830078 seconds ---
CUW  Infrastructure Data input Complete
--- 2020.9404790401459 seconds ---
CYP  Infrastructure Data input Complete
--- 2063.899358510971 seconds ---
CZE  Infrastructure Data input Complete
--- 2104.9339814186096 seconds ---
DNK  Infrastructure Data input Complete
--- 2142.0553691387177 seconds ---
DJI  Infrastructure Data input Complete
--- 2181.0842328071594 seconds ---
DMA  Infrastructure Data input Complete
--- 2219.4616017341614 seconds ---
DOM  Infrastructure Data input Complete
--- 2261.416271209717 seconds ---
ECU  Infrastructure Data input Complete
--- 2304.4672424793243 seconds ---
EGY  Infrastructure Data input Complete
--- 2344.8307807445526 seconds ---
SLV  Infrastructure Data input Complete
--- 2383.6463565826416 seconds ---
GNQ  Infrastructure Data input Complete
--- 2421.5372064113617 seconds ---
ERI  Infrastructure Data input Complete
--- 2459.867269039154 seconds ---
EST  Infrastructure Data input Complete
--- 2497.121540784836 seconds ---
SWZ  Infrastructure Data input Complete
--- 2533.668236732483 seconds ---
ETH  Infrastructure Data input Complete
--- 2573.581509590149 seconds ---
FRO  Infrastructure Data input Complete
--- 2612.363216161728 seconds ---
FJI  Infrastructure Data input Complete
--- 2654.384847164154 seconds ---
FIN  Infrastructure Data input Complete
--- 2692.4043831825256 seconds ---
FRA  Infrastructure Data input Complete
--- 2736.985600233078 seconds ---
PYF  Infrastructure Data input Complete
--- 2775.92861866951 seconds ---
GAB  Infrastructure Data input Complete
--- 2814.8875353336334 seconds ---
GMB  Infrastructure Data input Complete
--- 2857.380449771881 seconds ---
GEO  Infrastructure Data input Complete
--- 2896.7242364883423 seconds ---
DEU  Infrastructure Data input Complete
--- 2942.332807302475 seconds ---
GHA  Infrastructure Data input Complete
--- 2985.0500135421753 seconds ---
GIB  Infrastructure Data input Complete
--- 3025.555107831955 seconds ---
GRC  Infrastructure Data input Complete
--- 3068.214195251465 seconds ---
GRL  Infrastructure Data input Complete
--- 3117.0055952072144 seconds ---
GRD  Infrastructure Data input Complete
--- 3155.5781848430634 seconds ---
GUM  Infrastructure Data input Complete
--- 3196.431695461273 seconds ---
GTM  Infrastructure Data input Complete
--- 3236.9067902565002 seconds ---
GIN  Infrastructure Data input Complete
--- 3281.6218774318695 seconds ---
GNB  Infrastructure Data input Complete
--- 3321.9688110351562 seconds ---
GUY  Infrastructure Data input Complete
--- 3364.6828606128693 seconds ---
400
HTI  Infrastructure Data input Complete
--- 3407.9134991168976 seconds ---
HND  Infrastructure Data input Complete
--- 3449.9569911956787 seconds ---
HKG  Infrastructure Data input Complete
--- 3494.6367626190186 seconds ---
HUN  Infrastructure Data input Complete
--- 3532.245213985443 seconds ---
ISL  Infrastructure Data input Complete
--- 3574.7880625724792 seconds ---
IND  Infrastructure Data input Complete
--- 3613.3846945762634 seconds ---
IDN  Infrastructure Data input Complete
--- 3655.961172580719 seconds ---
IRN  Infrastructure Data input Complete
--- 3699.1478068828583 seconds ---
400
IRQ  Infrastructure Data input Complete
--- 3737.0897409915924 seconds ---
IRL  Infrastructure Data input Complete
--- 3777.3980107307434 seconds ---
IMN  Infrastructure Data input Complete
--- 3819.208592891693 seconds ---
ISR  Infrastructure Data input Complete
--- 3863.804797410965 seconds ---
ITA  Infrastructure Data input Complete
--- 3905.45618224144 seconds ---
JAM  Infrastructure Data input Complete
--- 3945.6733775138855 seconds ---
JPN  Infrastructure Data input Complete
--- 3986.0843403339386 seconds ---
JOR  Infrastructure Data input Complete
--- 4031.1251442432404 seconds ---
KAZ  Infrastructure Data input Complete
--- 4067.3407278060913 seconds ---
KEN  Infrastructure Data input Complete
--- 4112.371199131012 seconds ---
KIR  Infrastructure Data input Complete
--- 4156.690022945404 seconds ---
PRK  Infrastructure Data input Complete
--- 4199.30687212944 seconds ---
KOR  Infrastructure Data input Complete
--- 4247.669195175171 seconds ---
XKX  Infrastructure Data input Complete
--- 4291.169483423233 seconds ---
KWT  Infrastructure Data input Complete
--- 4331.852719545364 seconds ---
KGZ  Infrastructure Data input Complete
--- 4372.747261762619 seconds ---
LAO  Infrastructure Data input Complete
--- 4408.759717941284 seconds ---

LVA  Infrastructure Data input Complete
--- 4455.7121641635895 seconds ---
400
LBN  Infrastructure Data input Complete
--- 4502.4717972278595 seconds ---
LSO  Infrastructure Data input Complete
--- 4550.08488202095 seconds ---
LBR  Infrastructure Data input Complete
--- 4585.298866033554 seconds ---
LBY  Infrastructure Data input Complete
--- 4625.077467679977 seconds ---
LIE  Infrastructure Data input Complete
--- 4662.42559671402 seconds ---
LTU  Infrastructure Data input Complete
--- 4702.42996764183 seconds ---
LUX  Infrastructure Data input Complete
--- 4747.648330688477 seconds ---
MAC  Infrastructure Data input Complete
--- 4791.2149069309235 seconds ---
MDG  Infrastructure Data input Complete
--- 4832.3552277088165 seconds ---
MWI  Infrastructure Data input Complete
--- 4874.686292409897 seconds ---
MYS  Infrastructure Data input Complete
--- 4912.9489402771 seconds ---
MDV  Infrastructure Data input Complete
--- 4952.209278345108 seconds ---
MLI  Infrastructure Data input Complete
--- 4993.745920419693 seconds ---
MLT  Infrastructure Data input Complete
--- 5036.548361301422 seconds ---
MHL  Infrastructure Data input Complete
--- 5075.98278927803 seconds ---
MRT  Infrastructure Data input Complete
--- 5119.951860904694 seconds ---
MUS  Infrastructure Data input Complete
--- 5159.54464173317 seconds ---
MEX  Infrastructure Data input Complete
--- 5199.0197331905365 seconds ---
FSM  Infrastructure Data input Complete
--- 5239.434294462204 seconds ---
MDA  Infrastructure Data input Complete
--- 5277.063266515732 seconds ---
MCO  Infrastructure Data input Complete
--- 5318.012764453888 seconds ---
MNG  Infrastructure Data input Complete
--- 5356.654910802841 seconds ---
MNE  Infrastructure Data input Complete
--- 5400.771300315857 seconds ---
MAR  Infrastructure Data input Complete
--- 5448.088672637939 seconds ---
MOZ  Infrastructure Data input Complete
--- 5493.970385313034 seconds ---
MMR  Infrastructure Data input Complete
--- 5533.834066390991 seconds ---
NAM  Infrastructure Data input Complete
--- 5574.435383081436 seconds ---
NPL  Infrastructure Data input Complete
--- 5617.563015460968 seconds ---
NLD  Infrastructure Data input Complete
--- 5658.720082759857 seconds ---
NCL  Infrastructure Data input Complete
--- 5704.448973655701 seconds ---
NZL  Infrastructure Data input Complete
--- 5741.46769285202 seconds ---
NIC  Infrastructure Data input Complete
--- 5784.481689214706 seconds ---
NER  Infrastructure Data input Complete
--- 5821.833211421967 seconds ---
NGA  Infrastructure Data input Complete
--- 5861.99750828743 seconds ---
MKD  Infrastructure Data input Complete
--- 5898.124940633774 seconds ---
MNP  Infrastructure Data input Complete
--- 5936.03662276268 seconds ---
NOR  Infrastructure Data input Complete
--- 5976.141086578369 seconds ---
OMN  Infrastructure Data input Complete
--- 6020.605128288269 seconds ---
PAK  Infrastructure Data input Complete
--- 6065.046303033829 seconds ---
PLW  Infrastructure Data input Complete
--- 6103.7573437690735 seconds ---
PAN  Infrastructure Data input Complete
--- 6141.384995698929 seconds ---
PNG  Infrastructure Data input Complete
--- 6185.275456666946 seconds ---
PRY  Infrastructure Data input Complete
--- 6223.041569709778 seconds ---
PER  Infrastructure Data input Complete
--- 6263.071608543396 seconds ---
PHL  Infrastructure Data input Complete
--- 6299.54972577095 seconds ---
POL  Infrastructure Data input Complete
--- 6342.038560152054 seconds ---
PRT  Infrastructure Data input Complete
--- 6385.974349737167 seconds ---
PRI  Infrastructure Data input Complete
--- 6428.757163763046 seconds ---
QAT  Infrastructure Data input Complete
--- 6469.988486289978 seconds ---
ROU  Infrastructure Data input Complete
--- 6512.374762296677 seconds ---
400
RUS  Infrastructure Data input Complete
--- 6551.534336566925 seconds ---
RWA  Infrastructure Data input Complete
--- 6593.103085517883 seconds ---
WSM  Infrastructure Data input Complete
--- 6630.19270658493 seconds ---
SMR  Infrastructure Data input Complete
--- 6672.415398359299 seconds ---
STP  Infrastructure Data input Complete
--- 6714.437540531158 seconds ---
SAU  Infrastructure Data input Complete
--- 6753.868241786957 seconds ---
SEN  Infrastructure Data input Complete
--- 6796.518705368042 seconds ---
SRB  Infrastructure Data input Complete
--- 6838.806366443634 seconds ---
SYC  Infrastructure Data input Complete
--- 6877.438507080078 seconds ---
SLE  Infrastructure Data input Complete
--- 6922.458192586899 seconds ---
400
SGP  Infrastructure Data input Complete
--- 6966.886608362198 seconds ---
SXM  Infrastructure Data input Complete
--- 7010.1352434158325 seconds ---
SVK  Infrastructure Data input Complete
--- 7055.681707859039 seconds ---
SVN  Infrastructure Data input Complete
--- 7096.460428476334 seconds ---
SLB  Infrastructure Data input Complete
--- 7138.538047075272 seconds ---
SOM  Infrastructure Data input Complete
--- 7181.412927150726 seconds ---
ZAF  Infrastructure Data input Complete
--- 7223.3362238407135 seconds ---
SSD  Infrastructure Data input Complete
--- 7267.477134466171 seconds ---
400
ESP  Infrastructure Data input Complete
--- 7309.406286478043 seconds ---
LKA  Infrastructure Data input Complete
--- 7350.660420417786 seconds ---
KNA  Infrastructure Data input Complete
--- 7396.101329088211 seconds ---
LCA  Infrastructure Data input Complete
--- 7437.220981121063 seconds ---
MAF  Infrastructure Data input Complete
--- 7477.971781492233 seconds ---
VCT  Infrastructure Data input Complete
--- 7514.335993051529 seconds ---
SDN  Infrastructure Data input Complete
--- 7552.738709449768 seconds ---
SUR  Infrastructure Data input Complete
--- 7595.740921974182 seconds ---
SWE  Infrastructure Data input Complete
--- 7639.4563817977905 seconds ---
400
CHE  Infrastructure Data input Complete
--- 7681.687650203705 seconds ---
SYR  Infrastructure Data input Complete
--- 7724.996072769165 seconds ---
TJK  Infrastructure Data input Complete
--- 7770.9656894207 seconds ---
TZA  Infrastructure Data input Complete
--- 7810.108013391495 seconds ---
THA  Infrastructure Data input Complete
--- 7850.695330619812 seconds ---
TLS  Infrastructure Data input Complete
--- 7895.9164452552795 seconds ---
TGO  Infrastructure Data input Complete
--- 7933.804354667664 seconds ---
TON  Infrastructure Data input Complete
--- 7972.020966291428 seconds ---
TTO  Infrastructure Data input Complete
--- 8015.169622182846 seconds ---
TUN  Infrastructure Data input Complete
--- 8056.441494941711 seconds ---
TUR  Infrastructure Data input Complete
--- 8096.624389410019 seconds ---
TKM  Infrastructure Data input Complete
--- 8141.7313623428345 seconds ---
TCA  Infrastructure Data input Complete
--- 8180.678559541702 seconds ---
TUV  Infrastructure Data input Complete
--- 8215.546961545944 seconds ---
UGA  Infrastructure Data input Complete
--- 8250.440769672394 seconds ---
UKR  Infrastructure Data input Complete
--- 8289.71717453003 seconds ---
ARE  Infrastructure Data input Complete
--- 8328.081191301346 seconds ---
GBR  Infrastructure Data input Complete
--- 8369.689297914505 seconds ---
USA  Infrastructure Data input Complete
--- 8408.396935462952 seconds ---
URY  Infrastructure Data input Complete
--- 8450.185647964478 seconds ---
UZB  Infrastructure Data input Complete
--- 8489.877013921738 seconds ---
VUT  Infrastructure Data input Complete
--- 8529.940437078476 seconds ---
VEN  Infrastructure Data input Complete
--- 8567.422524929047 seconds ---
VNM  Infrastructure Data input Complete
--- 8607.440285921097 seconds ---
VIR  Infrastructure Data input Complete
--- 8647.386936187744 seconds ---
PSE  Infrastructure Data input Complete
--- 8687.326158046722 seconds ---
YEM  Infrastructure Data input Complete
--- 8731.41042804718 seconds ---
504
ZMB  Infrastructure Data input Complete
--- 8889.867902755737 seconds ---
ZWE  Infrastructure Data input Complete
--- 8928.538575410843 seconds ---
Infrastructure Tables Complete
--- 8928.539572954178 seconds ---

In [2]:
### Fill Other Factors Tables 2010-2019 in Database
import requests
import json
import pandas as pd
import time
import psycopg2

# try:
connection = psycopg2.connect(
    database="unrestdatabase", user='postgres', password='password', host='127.0.0.1', port='5432'
)

cursor = connection.cursor()

countries_query = "select country_code from countries"
cursor.execute(countries_query)
print ("Fetching country codes")
countries = cursor.fetchall()

cc_list = []

for cc in countries:
    cc_list.append(cc[0])
print ("CC list created")

other_indicator_query = "select indicator_code from other_factors"
cursor.execute(other_indicator_query)
print ("Fetching Other Indicator Codes")
other_indicators = cursor.fetchall()

other_indicator_list = []
for indicator in other_indicators:
    other_indicator_list.append(indicator[0].strip())
print ("Indicator code list created")

start_time = time.time()
for cc in cc_list:
    
    ### If api calls time out, I don't want to repeat table entries, so checking if they exist and moving on if they do
    check_statement = 'select * from other_2019 where "COUNTRY.CODE" =  ' + "'" + cc + "'"
    cursor.execute(check_statement)
    if bool(cursor.rowcount):
        continue
        
    values_dict_2010 = {'COUNTRY.CODE': cc}   ### dictionaries to hold values pulled from API
    values_dict_2011 = {'COUNTRY.CODE': cc}
    values_dict_2012 = {'COUNTRY.CODE': cc}   
    values_dict_2013 = {'COUNTRY.CODE': cc}   
    values_dict_2014 = {'COUNTRY.CODE': cc}   
    values_dict_2015 = {'COUNTRY.CODE': cc}   
    values_dict_2016 = {'COUNTRY.CODE': cc}   
    values_dict_2017 = {'COUNTRY.CODE': cc}   
    values_dict_2018 = {'COUNTRY.CODE': cc}   
    values_dict_2019 = {'COUNTRY.CODE': cc}     

    for indicator in other_indicators:
        time.sleep(1)  ### Delay for API calls
        indicator_in = indicator[0].strip()
        url = ("http://api.worldbank.org/v2/country/%s/indicator/%s?format=json" % (cc, indicator_in))
        r = requests.get(url = url)
        if r.status_code == 200:
            data_pull = r.json()
            data_pull = json.dumps(data_pull)
            data_pull = json.loads(data_pull)
            
            ### years 2010 - 2019 correspond to indices 10 - 1, respectively
            values_dict_2010[indicator_in] = data_pull[1][10]['value']
            values_dict_2011[indicator_in] = data_pull[1][9]['value']
            values_dict_2012[indicator_in] = data_pull[1][8]['value']
            values_dict_2013[indicator_in] = data_pull[1][7]['value']
            values_dict_2014[indicator_in] = data_pull[1][6]['value']
            values_dict_2015[indicator_in] = data_pull[1][5]['value']
            values_dict_2016[indicator_in] = data_pull[1][4]['value']
            values_dict_2017[indicator_in] = data_pull[1][3]['value']
            values_dict_2018[indicator_in] = data_pull[1][2]['value']
            values_dict_2019[indicator_in] = data_pull[1][1]['value']

        else:
            print(r.status_code)
            continue
        
    
    ### 2010 Other Data
    insert_statement = """INSERT INTO other_2010 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2010.items():
        count += 1
        if count < len(values_dict_2010):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2011 Other Data    
    insert_statement = """INSERT INTO other_2011 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2011.items():
        count += 1
        if count < len(values_dict_2011):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2012 Other Data
    insert_statement = """INSERT INTO other_2012 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2012.items():
        count += 1
        if count < len(values_dict_2012):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2013 Other Data
    insert_statement = """INSERT INTO other_2013 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2013.items():
        count += 1
        if count < len(values_dict_2013):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2014 Other Data    
    insert_statement = """INSERT INTO other_2014 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2014.items():
        count += 1
        if count < len(values_dict_2014):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2015 Other Data
    insert_statement = """INSERT INTO other_2015 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2015.items():
        count += 1
        if count < len(values_dict_2015):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2016 Other Data
    insert_statement = """INSERT INTO other_2016 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2016.items():
        count += 1
        if count < len(values_dict_2016):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2017 Other Data
    insert_statement = """INSERT INTO other_2017 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2017.items():
        count += 1
        if count < len(values_dict_2017):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    

    ### 2018 Other Data    
    insert_statement = """INSERT INTO other_2018 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2018.items():
        count += 1
        if count < len(values_dict_2018):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    
    ### 2019 Other Data
    insert_statement = """INSERT INTO other_2019 ("""
    insert_ind = ""
    insert_val = ""
    count = 0
    for ind, val in values_dict_2019.items():
        count += 1
        if count < len(values_dict_2019):
            insert_ind = insert_ind + '"' + ind + '", '
            insert_val = insert_val + "'" + str(val) + "'" + ", "  
        else:
            insert_ind = insert_ind + '"' + ind + '") '
            insert_val = insert_val + "'" + str(val) + "'" + ");"   
    insert_statement = insert_statement + insert_ind + " VALUES (" + insert_val
    cursor.execute(insert_statement)    
    

    connection.commit()
    print(cc, " Other Data input Complete")
    print("--- %s seconds ---" % (time.time() - start_time))   


cursor.close()
connection.close()    
    
print("Other Tables Complete")    
print("--- %s seconds ---" % (time.time() - start_time))    
    
# except (Exception, psycopg2.Error) as error :
#     print ("Error while fetching data from database", error)

# finally:
#     #closing database connection.
#     if(connection):
#         cursor.close()
#         connection.close()
#         print("Database connection is closed")

Fetching country codes
CC list created
Fetching Other Indicator Codes
Indicator code list created
TUR  Other Data input Complete
--- 31.886215209960938 seconds ---
TKM  Other Data input Complete
--- 68.41831970214844 seconds ---
TCA  Other Data input Complete
--- 99.52035665512085 seconds ---
TUV  Other Data input Complete
--- 134.13285946846008 seconds ---
UGA  Other Data input Complete
--- 169.48142051696777 seconds ---
UKR  Other Data input Complete
--- 200.18211698532104 seconds ---
ARE  Other Data input Complete
--- 234.2539472579956 seconds ---
GBR  Other Data input Complete
--- 271.78463196754456 seconds ---
USA  Other Data input Complete
--- 301.7614526748657 seconds ---
URY  Other Data input Complete
--- 334.54312229156494 seconds ---
UZB  Other Data input Complete
--- 369.0360059738159 seconds ---
VUT  Other Data input Complete
--- 402.84813237190247 seconds ---
VEN  Other Data input Complete
--- 437.1822259426117 seconds ---
VNM  Other Data input Complete
--- 474.12136244773865 seconds ---
VIR  Other Data input Complete
--- 512.1370739936829 seconds ---
PSE  Other Data input Complete
--- 544.4370748996735 seconds ---
YEM  Other Data input Complete
--- 576.7471599578857 seconds ---
ZMB  Other Data input Complete
--- 609.0711867809296 seconds ---
ZWE  Other Data input Complete
--- 647.5004127025604 seconds ---
Other Tables Complete
--- 647.5014107227325 seconds ---

In [1]:
### Pull in protests and riots data from 2010 ACLED data
import pandas as pd

df10 = pd.read_csv('acled/protests_riots_2010.csv')

df10_protests = df10[(df10.event_type == 'Protests')]
df10_protests_country = df10_protests.groupby("country")
df10_protests_counts = df10_protests_country.count()
df10_protests_counts = df10_protests_counts[['data_id']]
df10_protests_counts.reset_index(inplace=True)
df10_protests_counts = df10_protests_counts.rename(columns = {'index':'country'})
df10_protests_counts = df10_protests_counts.rename(columns = {"data_id": "Protest_Count_2010"})

df10_riots = df10[(df10.event_type == 'Riots')]
df10_riots_country = df10_riots.groupby("country")
df10_riots_counts = df10_riots_country.count()
df10_riots_counts = df10_riots_counts[['data_id']]
df10_riots_counts.reset_index(inplace=True)
df10_riots_counts = df10_riots_counts.rename(columns = {'index':'country'})
df10_riots_counts = df10_riots_counts.rename(columns = {"data_id": "Riot_Count_2010"})

In [2]:
df10_protests_counts

                         country  Protest_Count_2010
0                        Algeria                   8
1                     Bangladesh                 576
2                          Benin                   9
3                   Burkina Faso                   3
4                        Burundi                   3
5                       Cambodia                 180
6                       Cameroon                   4
7       Central African Republic                   4
8   Democratic Republic of Congo                   4
9                       Djibouti                   2
10                         Egypt                  46
11                      Ethiopia                   4
12                         Gabon                   2
13                         Ghana                   6
14                        Guinea                   3
15                 Guinea-Bissau                   1
16                   Ivory Coast                  53
17                         Kenya                  46
18                       Lesotho                   2
19                       Liberia                   2
20                         Libya                   1
21                    Madagascar                   7
22                        Malawi                   3
23                          Mali                   2
24                    Mauritania                   6
25                       Morocco                   8
26                       Myanmar                  49
27                       Namibia                   9
28                         Nepal                 216
29                         Niger                   2
30                       Nigeria                  99
31                      Pakistan                3549
32                        Rwanda                   1
33                       Senegal                  10
34                  Sierra Leone                   7
35                       Somalia                  75
36                  South Africa                 150
37                     Sri Lanka                 110
38                         Sudan                  13
39                      Tanzania                   1
40                      Thailand                 186
41                          Togo                  17
42                       Tunisia                  22
43                        Uganda                  16
44                       Vietnam                   9
45                        Zambia                   3
46                      Zimbabwe                  19
47                      eSwatini                   4

In [3]:
len(df10_protests_counts)

48

In [4]:
df10_riots_counts

                         country  Riot_Count_2010
0                        Algeria               10
1                     Bangladesh             1138
2                       Botswana                1
3                   Burkina Faso                1
4                        Burundi                3
5                       Cambodia               22
6       Central African Republic                1
7   Democratic Republic of Congo                7
8                          Egypt               24
9                       Ethiopia                1
10                         Gabon                1
11                         Ghana                1
12                        Guinea                3
13                   Ivory Coast               28
14                         Kenya               19
15                       Liberia                3
16                    Madagascar                1
17                          Mali                1
18                    Mauritania                2
19                       Morocco                1
20                    Mozambique               12
21                         Nepal              221
22                         Niger                1
23                       Nigeria               47
24                      Pakistan              334
25                        Rwanda                1
26                       Senegal                1
27                  Sierra Leone                2
28                       Somalia                6
29                  South Africa              130
30                     Sri Lanka              116
31                         Sudan                5
32                      Thailand               36
33                          Togo                1
34                       Tunisia                4
35                        Uganda               27
36                       Vietnam                3
37                        Zambia                6
38                      Zimbabwe                5

In [5]:
len(df10_riots_counts)

39

In [6]:
df10_counts = pd.merge(df10_protests_counts, df10_riots_counts, how='outer', sort=True, on='country')

In [7]:
df10_counts

                         country  Protest_Count_2010  Riot_Count_2010
0                        Algeria                 8.0             10.0
1                     Bangladesh               576.0           1138.0
2                          Benin                 9.0              NaN
3                       Botswana                 NaN              1.0
4                   Burkina Faso                 3.0              1.0
5                        Burundi                 3.0              3.0
6                       Cambodia               180.0             22.0
7                       Cameroon                 4.0              NaN
8       Central African Republic                 4.0              1.0
9   Democratic Republic of Congo                 4.0              7.0
10                      Djibouti                 2.0              NaN
11                         Egypt                46.0             24.0
12                      Ethiopia                 4.0              1.0
13                         Gabon                 2.0              1.0
14                         Ghana                 6.0              1.0
15                        Guinea                 3.0              3.0
16                 Guinea-Bissau                 1.0              NaN
17                   Ivory Coast                53.0             28.0
18                         Kenya                46.0             19.0
19                       Lesotho                 2.0              NaN
20                       Liberia                 2.0              3.0
21                         Libya                 1.0              NaN
22                    Madagascar                 7.0              1.0
23                        Malawi                 3.0              NaN
24                          Mali                 2.0              1.0
25                    Mauritania                 6.0              2.0
26                       Morocco                 8.0              1.0
27                    Mozambique                 NaN             12.0
28                       Myanmar                49.0              NaN
29                       Namibia                 9.0              NaN
30                         Nepal               216.0            221.0
31                         Niger                 2.0              1.0
32                       Nigeria                99.0             47.0
33                      Pakistan              3549.0            334.0
34                        Rwanda                 1.0              1.0
35                       Senegal                10.0              1.0
36                  Sierra Leone                 7.0              2.0
37                       Somalia                75.0              6.0
38                  South Africa               150.0            130.0
39                     Sri Lanka               110.0            116.0
40                         Sudan                13.0              5.0
41                      Tanzania                 1.0              NaN
42                      Thailand               186.0             36.0
43                          Togo                17.0              1.0
44                       Tunisia                22.0              4.0
45                        Uganda                16.0             27.0
46                       Vietnam                 9.0              3.0
47                        Zambia                 3.0              6.0
48                      Zimbabwe                19.0              5.0
49                      eSwatini                 4.0              NaN

In [8]:
len(df10_counts)

50

In [9]:
### Bring in country codes to link to eventually link to world bank data
acled_cc = pd.read_csv('acled/acled_cc.csv')

acled_cc = [acled_cc["Country"], acled_cc["CC"], acled_cc["Region"]]
headers = ["country", "Country_Code", "Region"]

acled_df = pd.concat(acled_cc, axis=1, keys=headers)

In [10]:
acled_df

                  country Country_Code                     Region
0                 Algeria          DZA                     Africa
1                  Angola          AGO                     Africa
2                   Benin          BEN                     Africa
3                Botswana          BWA                     Africa
4            Burkina Faso          BFA                     Africa
..                    ...          ...                        ...
138            Uzbekistan          UZB  Caucasus and Central Asia
139             Venezuela          VEN              Latin America
140               Vietnam          VNM                       Asia
141  Virgin Islands, U.S.          VIR              Latin America
142                 Yemen          YEM                Middle East

[143 rows x 3 columns]

In [11]:
df10_toDB = pd.merge(df10_counts, acled_df, how='inner', sort=True, on='country')

In [12]:
df10_toDB

,country,Protest_Count_2010,Riot_Count_2010,Country_Code,Region
0,Algeria,8.0,10.0,DZA,Africa
1,Bangladesh,576.0,1138.0,BGD,Asia
2,Benin,9.0,NaN,BEN,Africa
3,Botswana,NaN,1.0,BWA,Africa
4,Burkina Faso,3.0,1.0,BFA,Africa
5,Burundi,3.0,3.0,BDI,Africa
6,Cambodia,180.0,22.0,KHM,Asia
7,Cameroon,4.0,NaN,CMR,Africa
8,Central African Republic,4.0,1.0,CAF,Africa
9,Democratic Republic of Congo,4.0,7.0,COD,Africa
10,Djibouti,2.0,NaN,DJI,Africa
11,Egypt,46.0,24.0,EGY,Africa
12,Ethiopia,4.0,1.0,ETH,Africa
13,Gabon,2.0,1.0,GAB,Africa
14,Ghana,6.0,1.0,GHA,Africa
15,Guinea,3.0,3.0,GIN,Africa
16,Guinea-Bissau,1.0,NaN,GNB,Africa
17,Ivory Coast,53.0,28.0,CIV,Africa
18,Kenya,46.0,19.0,KEN,Africa
19,Lesotho,2.0,NaN,LSO,Africa
20,Liberia,2.0,3.0,LBR,Africa
21,Libya,1.0,NaN,LBY,Africa
22,Madagascar,7.0,1.0,MDG,Africa
23,Malawi,3.0,NaN,MWI,Africa
24,Mali,2.0,1.0,MLI,Africa
25,Mauritania,6.0,2.0,MRT,Africa
26,Morocco,8.0,1.0,MAR,Africa
27,Mozambique,NaN,12.0,MOZ,Africa
28,Myanmar,49.0,NaN,MMR,Asia
29,Namibia,9.0,NaN,NAM,Africa
30,Nepal,216.0,221.0,NPL,Asia
31,Niger,2.0,1.0,NER,Africa
32,Nigeria,99.0,47.0,NGA,Africa
33,Pakistan,3549.0,334.0,PAK,Asia
34,Rwanda,1.0,1.0,RWA,Africa
35,Senegal,10.0,1.0,SEN,Africa
36,Sierra Leone,7.0,2.0,SLE,Africa
37,Somalia,75.0,6.0,SOM,Africa
38,South Africa,150.0,130.0,ZAF,Africa
39,Sri Lanka,110.0,116.0,LKA,Asia
40,Sudan,13.0,5.0,SDN,Africa
41,Tanzania,1.0,NaN,TZA,Africa
42,Thailand,186.0,36.0,THA,Asia
43,Togo,17.0,1.0,TGO,Africa
44,Tunisia,22.0,4.0,TUN,Africa
45,Uganda,16.0,27.0,UGA,Africa
46,Vietnam,9.0,3.0,VNM,Asia
47,Zambia,3.0,6.0,ZMB,Africa
48,Zimbabwe,19.0,5.0,ZWE,Africa
49,eSwatini,4.0,NaN,SWZ,Africa

In [13]:
### Write data to database

from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:password@127.0.0.1:5432/unrestdatabase')
df10_toDB.to_sql('acled_2010', engine)

In [23]:
import os

for file in os.listdir('acled'):
    if file.startswith('protests'):
        print(file)
        table_name = "acled_" + file[-8:-4]
        print(table_name)

protests_riots_2010.csv
acled_2010
protests_riots_2011.csv
acled_2011
protests_riots_2012.csv
acled_2012
protests_riots_2013.csv
acled_2013
protests_riots_2014.csv
acled_2014
protests_riots_2015.csv
acled_2015
protests_riots_2016.csv
acled_2016
protests_riots_2017.csv
acled_2017
protests_riots_2018.csv
acled_2018
protests_riots_2019.csv
acled_2019

In [29]:
### Write acled data to database

import os
from sqlalchemy import create_engine

acled_cc = pd.read_csv('acled/acled_cc.csv')
acled_cc = [acled_cc["Country"], acled_cc["CC"], acled_cc["Region"]]
headers = ["country", "Country_Code", "Region"]
acled_df = pd.concat(acled_cc, axis=1, keys=headers)


for filename in os.listdir('acled'): ### Placed acled files in folder in directory 'acled'
    if filename.startswith('protests'):  ### acled exported csvs are titled like protests_riots_2010.csv
        year = filename[-8:-4]    
           
        file = 'acled/' + filename   
        df = pd.read_csv(file)

        protest_column = "Protest_Count_" + year
        df_protests = df[(df.event_type == 'Protests')]
        df_protests_country = df_protests.groupby("country")
        df_protests_counts = df_protests_country.count()
        df_protests_counts = df_protests_counts[['data_id']]
        df_protests_counts.reset_index(inplace=True)
        df_protests_counts = df_protests_counts.rename(columns = {'index':'country'})
        df_protests_counts = df_protests_counts.rename(columns = {"data_id": protest_column})

        riot_column = "Riot_Count_" + year
        df_riots = df[(df.event_type == 'Riots')]
        df_riots_country = df_riots.groupby("country")
        df_riots_counts = df_riots_country.count()
        df_riots_counts = df_riots_counts[['data_id']]
        df_riots_counts.reset_index(inplace=True)
        df_riots_counts = df_riots_counts.rename(columns = {'index':'country'})
        df_riots_counts = df_riots_counts.rename(columns = {"data_id": riot_column})

        df_counts = pd.merge(df_protests_counts, df_riots_counts, how='outer', sort=True, on='country')

        df_toDB = pd.merge(df_counts, acled_df, how='inner', sort=True, on='country')

        table_name = "acled_" + year
        engine = create_engine('postgresql://postgres:password@127.0.0.1:5432/unrestdatabase')
        df_toDB.to_sql(table_name, engine)
        print("ACLED Table for", year, "created.")

ACLED Table for 2010 created.
ACLED Table for 2011 created.
ACLED Table for 2012 created.
ACLED Table for 2013 created.
ACLED Table for 2014 created.
ACLED Table for 2015 created.
ACLED Table for 2016 created.
ACLED Table for 2017 created.
ACLED Table for 2018 created.
ACLED Table for 2019 created.